### ISSUE TITLE
Emoticon selector shows a half of current emoticon

### ISSUE THREAD

**Issue by hprmedina** [ksnip/kImageAnnotator#104]
When using the emoticon selector, it appears only a half of the image (see number 1), and when the combobox of the images are extended, try to move the window editor, the windows moves but the icons stay in the same position XD (see number 2) fun!!

![image](https://user-images.githubusercontent.com/18145927/83271849-66cc7e00-a198-11ea-8f1d-b906b533dd5c.png)
ok, same with others popup XD
![image](https://user-images.githubusercontent.com/18145927/83272365-0b4ec000-a199-11ea-8703-fb05ade31748.png)

-----------------------------------------------------------
Version: 1.7.0-continuous
Build: 1201-62a4d1e

Using:
Qt5
X11
KDE Wayland
Gnome Wayland

**Comment by DamirPorobic** [comment]
Can you send me quick a screenshot of another settings widget, for example the fill picker? How does that one behave?

**Comment by DamirPorobic** [comment]
Should be fixed now, I've created a new widget for the stickers.

**Comment by hprmedina** [comment]
Perfect!!!, thanks.
![image](https://user-images.githubusercontent.com/18145927/83802721-49585200-a679-11ea-8862-5f1432670551.png)

Sorry... fillpicker, 
![image](https://user-images.githubusercontent.com/18145927/83802793-67be4d80-a679-11ea-9eb5-3eaec15b303e.png)

**Comment by DamirPorobic** [comment]
I'm fixing that one too.

**Comment by DamirPorobic** [comment]
@hprmedina fillpicker should work now too.
