### ISSUE TITLE
Copy area size differs from last capture

### ISSUE THREAD

**Issue by hprmedina** [ksnip/kImageAnnotator#107]
Hi...here I'm again testing... XD, I found an issue when not using tabs

First in settings:
- unSelect "Use Tabs"
- Close Ksnip for use this configuration.

steps:
1.- Take a "first" big capture ... 100x100 about, then ksnip shows the editor and the canvas is the same size from capture.
2.- Click on "New" rectangular area, but now take a "second" small capture, 10x10 or about, then ksnip replace the image from the unique tab (remember we not have tabs now), and show it in the editor.
3.- Click on "Copy", and paste the image on a document. The image pasted contains the second image at left upper surrounded by a blank space with the size of the "first" image.

When we use tabs, this problems not happens. Open the next image on other tab 
![image](https://user-images.githubusercontent.com/18145927/84706825-a979ae80-af2b-11ea-9873-4a258e5c920b.png)

---
Version: 1.7.0-continuous
Build: 1218-023a1cb

Using:
Qt5
X11
KDE Wayland
Gnome Wayland

**Comment by DamirPorobic** [comment]
Thanks for the detailed steps, I'll have a look at it.

**Comment by DamirPorobic** [comment]
Have you tried with latest version? This seems to be working for me. I've captured a large picture, then a small one and copied it to clipboard and pasted it in a document and it was only the small picture. 

There was actually a fix that could have resolved this few commits ago. Could you test with latest AppImage?

**Comment by DamirPorobic** [comment]
Oh, I see from your comment you're using already the latest version.

**Comment by hprmedina** [comment]
Yes, I always downloads the last "continuous build" to confirm if the problem is already resolved before to report, and now I downloaded again (for insure) and the problem persists, the version is the same.

**Comment by DamirPorobic** [comment]
With what OS is this happening?

________________________________

**Comment by hprmedina** [comment]
Opensuse Leap 15.2, GNOME Shell 3.34.4, Wayland

**Comment by DamirPorobic** [comment]
Oh, you're using GNOME Wayland. Will try that next, I'm downloading the iso as I write this.

**Comment by hprmedina** [comment]
No, is more complicated! is a combination, Select "Automatically copy new captures to clipboard" too! and try again.

**Comment by DamirPorobic** [comment]
Ah, yes, now I got it.

**Comment by DamirPorobic** [comment]
I think the issue is that the QGrahicsScene never shrinks, only can grow https://doc.qt.io/qt-5/qgraphicsscene.html#sceneRect-prop

I'm trying to implement a workaround.

**Comment by DamirPorobic** [comment]
I think I got a fix, worked on my machine now. The CI needs a couple of minutes before you can test.

**Comment by hprmedina** [comment]
Nice work, fixed!
