### ISSUE TITLE
Keeps popping up to be updated when I have the latest

### ISSUE THREAD

**Issue by SecretAgentAgentX** [ksnip/kImageAnnotator#109]
For what I believe is the 4th time now when I do updates either through Pamac or use Topgrade this wants to be updated even though it updated just fine according to the updater's out put. Running Manjaro KDE 20.0.3 testing build.

**Comment by DamirPorobic** [comment]
Not sure what I can say about it, I don't know any of those two services you mentioned, I'm not doing the packaging. What version kImageAnnotator do you have and what version it's saying you should update to? The only think that comes to my mind is that you have version `0.3.0` which is currently work in progress and I commit changes to it all the time, so this might be one source of those updates. That being said, I'm not sure if you should be relying on a version that is "work in progress", might break any time. When the version is finished it gets a tag and after a tag was set the version should get no more updates. So those two services that you mentioned should be using the tagged versions.

**Comment by DamirPorobic** [comment]
As I haven't heard from you for some time I'm going to close this issue. Feel free to open it again if you need further assistance.
