### ISSUE TITLE
Please make line and arrow in separate buttons

### ISSUE THREAD

**Issue by MurzNN** [ksnip/kImageAnnotator#112]
Line and Arrow tools now collapsed in one button, but very often needed both tools, so will be good to make separate buttons for each tool.

**Comment by DamirPorobic** [comment]
They're kind of the same think and with latest version it shouldn't be that difficult to select one then other, the tool popup comes now instantly.

**Comment by DamirPorobic** [comment]
Been thinking about this one and I think I wont implement it, it would create too much buttons and we have already not much space there. Maybe using keyboard shortcuts can help you here?
