### ISSUE TITLE
Snap lines to degrees not working when CTRL pressed before clicking annotation area

### ISSUE THREAD

**Issue by MurzNN** [ksnip/kImageAnnotator#113]
Very often I need to draw horizontal or vertical line, but this is not too easy with current behavior. Can you implement snap line to rounded degrees, when Ctrl is pressed, like in Inkscape and many other editors?

**Comment by MurzNN** [comment]
Wow, this works! But not always, when I click on tool button and start drawing - this not works, but at second try - works/

**Comment by DamirPorobic** [comment]
Can you write down the exact steps that produce the not working behavior?

________________________________

**Comment by MurzNN** [comment]
1. Open ksnip window, press 'Capture', make capture.
2. Click on "Line" tool in left toolbar.
3. Hold Ctrl and start drawing (or start drawing and press Ctrl later) - snap will not work.
4. Stop drawing, and start again. Ctrl becomes work!

**Comment by DamirPorobic** [comment]
Ah yes, I think I know the reason. The widget that is listening for key press events has not yet the focus  when you just click on the button and right away the CTRL Key. I'll see if I can do something there.

**Comment by DamirPorobic** [comment]
Fixed in 0.3.1
