### ISSUE TITLE
Crashes after undoing a number annotation

### ISSUE THREAD

**Issue by dflogeras** [ksnip/kImageAnnotator#114]
- Create a new snapshot, then select the numbering tool (with or without pointer)
- Add a single number
- Press CTRL-Z to undo
- Then add two more numbers.  It crashes consistently for me when adding the second.

I tried both built from source as well as the AppImage on 64bit Linux.

**Comment by DamirPorobic** [comment]
Should be fixed now, a one liner. I'll wait till tomorrow or so if somebody else reports any crashes before releasing `1.7.1`

**Comment by dflogeras** [comment]
Thank you. I will test that ASAP.

I'm trying to package for Gentoo, and have found kImageAnnotator is installing the translation files to an unexpected place.  I'm not yet sure if it's anything in the build system, or if it isn't a Gentoo problem (well, me problem. I'm very new at this).  I'll report ASAP if I find anything in the cmake.

**Comment by dflogeras** [comment]
PS I tested the undo crash here and it works both on the nightly AppImage, as well as built from source on Gentoo.
