### ISSUE TITLE
Some words are missing for translation

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#116]
Some words are missing for translation

<a href="https://ibb.co/fMzjT9H"><img src="https://i.ibb.co/8ML1Qb9/anotador1.jpg" alt="anotador1" border="0"></a>

*---------------------------*

<a href="https://imgbb.com/"><img src="https://i.ibb.co/TrgnqFb/anotador2.jpg" alt="anotador2" border="0"></a>

*---------------------------*

<a href="https://imgbb.com/"><img src="https://i.ibb.co/85hvBt9/anotador3.jpg" alt="anotador3" border="0"></a>

*---------------------------*

<a href="https://imgbb.com/"><img src="https://i.ibb.co/p11Cj1P/anotador4.jpg" alt="anotador4" border="0"></a>

**Comment by DamirPorobic** [comment]
Good Point, need to refresh the translations. Will do that today.

**Comment by DamirPorobic** [comment]
Should be now up to date

**Comment by antrrax** [comment]
I noticed now, this string was also missing:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/nC2g82C/anotador002.jpg" alt="anotador002" border="0"></a>

**Comment by DamirPorobic** [comment]
Thats a Qt string, belongs to the other ticket with all the qt stuff.

________________________________
