### ISSUE TITLE
Undo removes several or all items

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#121]
I add an object, for example an arrow, then select that arrow and delete it.

If I try to use the redo command, nothing happens.

the arrow that was deleted does not appear again

**Comment by antrrax** [comment]
note:
using the keyboard shortcut Ctrl + Z

**Comment by DamirPorobic** [comment]
I was able to reproduce the issue with deleting all items and I'm testing a fix right now but I was not able to reproduce the item not restored after deleting. This seems to be working or it was related to the  other issue but can't see how.

**Comment by antrrax** [comment]
I tested version 1.7.1 that is available on github released yesterday. And there was no change
I'm testing on Windows 10

I typed three different text boxes and clicked Ctrl + Z and is still deleting all objects in the image

**Comment by DamirPorobic** [comment]
Same here, let me build ksnip again.

________________________________

**Comment by antrrax** [comment]
I tested on Windows 10 and now apparent corrected this error

**Comment by DamirPorobic** [comment]
Glad to hear
