### ISSUE TITLE
Zoom in and out

### ISSUE THREAD

**Issue by adrianocr** [ksnip/kImageAnnotator#123]
Feature request: allow zooming in and out of the captured image. Sometimes it's useful to get a zoomed out "overview" of what you captured. Likewise sometimes it'd useful to zoom in to be able to better highlight or box something in specific.

**Comment by DamirPorobic** [comment]
I'll try to get this into `0.4.0`

**Comment by fpohtmeh-github** [comment]
Implemented in #135

**Comment by DamirPorobic** [comment]
This is now available in the latest release.

**Comment by grahamperrin** [comment]
FreeBSD bug [252315 – graphics/ksnip zoom field does not respond to click, and the percentage can not be altered](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252315)

**Comment by DamirPorobic** [comment]
Don't think that this is a bug, this field is on purpose read-only and should be only used to visualize current zoom level. Zoom in/out is done currently only with mouse wheel.

**Comment by grahamperrin** [comment]
@DamirPorobic thank you. Shall I close the bug in the FreeBSD area and open an issue here? 

_Input: do not require mouse wheels_

(I have a trackball, but nothing like a mouse wheel.)

**Comment by DamirPorobic** [comment]
@grahamperrin I'll open a new feature request to enable zoom in/out with keyboard shortcuts.
