### ISSUE TITLE
Build issues (FreeBSD), with fixes

### ISSUE THREAD

**Issue by adriaandegroot** [ksnip/kImageAnnotator#124]
- Linking X11; in `CMakeLists.txt` with modern `FindX11.cmake`, you want `target_link_libraries(kImageAnnotator PRIVATE X11::X11)`. You're missing the namespace right now.
- `KIMAGEANNOTATOR_LANG_INSTAL_DIR` mis-spells *INSTALL* and, while you use it consistently, is hard to read
- `CMAKE_INSTALL_DATAROOTDIR`, used in the definition of the translations-install-dir, doesn't seem to exist at that point in the file; you want to move the include of GNUInstallDirs up even higher (I'd suggest right after setting C++ standard and AUTOMOC).

**Comment by DamirPorobic** [comment]
Hi Adrian

> Linking X11; in CMakeLists.txt with modern FindX11.cmake, you want target_link_libraries(kImageAnnotator PRIVATE X11::X11). You're missing the namespace right now.

This only works with CMAKE versions >= `3.14` which not everyone has, for example me or the CI that builds ksnip, see #87 

> KIMAGEANNOTATOR_LANG_INSTAL_DIR mis-spells INSTALL and, while you use it consistently, is hard to read

Good point, thanks, will fix that.

> CMAKE_INSTALL_DATAROOTDIR, used in the definition of the translations-install-dir, doesn't seem to exist at that point in the file; you want to move the include of GNUInstallDirs up even higher (I'd suggest right after setting C++ standard and AUTOMOC).

Should be fixed already, see #115

**Comment by adriaandegroot** [comment]
I see #87 is from tcberner, the other half of the FreeBSD kde@ packaging team. This particular link problem is weird, since linking to just-plain `X11` fails .. which makes sense, because on FreeBSD X11 isn't in the default linker library search paths, and you need to `target_link_directories(... ${X11_LIBRARY_DIRS})`. On Linux that isn't an issue. 

We'll just continue to patch this in packaging, no problem.

I hadn't looked very hard for issue-duplicates, so I've got a #115 -alike patch in packaging 0.3.0, which I can drop when 0.3.1 comes out.

**Comment by DamirPorobic** [comment]
Will fix the typo later today, you can expect it in `0.3.1` too.

**Comment by DamirPorobic** [comment]
Typos should be fixed now, in ksnip too, had the same typo there.
