### ISSUE TITLE
Kimageannotator now available in Debian (and its derivatives in future)

### ISSUE THREAD

**Issue by hosiet** [ksnip/kImageAnnotator#125]
Hi, you may now find the packaged kimageannotator library at https://tracker.debian.org/pkg/kimageannotator . It is appearing as shared libraries and the packaging scripts are located at https://salsa.debian.org/debian/kimageannotator .

It was just accepted in Debian's archive and it will take some time before the new v0.3.0 gets updated due to the ongoing Qt 5.12 -> Qt 5.14 transition in Debian Sid/Unstable. I will be handling that (as well as providing the new translation files in those packages, as discussed before) later.

The milestone would be having ksnip into Debian (and derivatives) and we are now closer to that target. I will notify that when it's done.

**Comment by DamirPorobic** [comment]
I'll be releasing kImageAnnotator `0.3.1` and ksnip `1.7.1` today or tomorrow, might be better to use those versions for the Debian release, they're bug fix releases, should be more stable then `0.3.0` and `1.7.0`.
