### ISSUE TITLE
Add a new tool for creating resizable movable duplicates of regions

### ISSUE THREAD

**Issue by epic6666** [ksnip/kImageAnnotator#131]
This is the sixth thing discussed in this issue: https://github.com/ksnip/ksnip/issues/364

**Comment by DamirPorobic** [comment]
I'm having in mind drawing a rect and when finished drawing it becomes a copy of the region below it after which it can be resized and moved around like any other item.

**Comment by DamirPorobic** [comment]
@fnkabit thanks for implementing this feature!
