### ISSUE TITLE
Add drop shadow to captured images

### ISSUE THREAD

**Issue by ricapur** [ksnip/kImageAnnotator#133]
Add drop shadow to the overall images. I currently achieve this by pasting the image to GIMP and then applying Flters -> Light and Shadow -> Drop Shadow (Legacy),
I use this so it creates a professional look at the time it lets others to clearly identify the image boundaries.
See below the results:

![image](https://user-images.githubusercontent.com/55522705/87381382-8fe77900-c562-11ea-85b7-cb116c9db30c.png)

**Comment by DamirPorobic** [comment]
Thanks for opening this feature request.

**Comment by DamirPorobic** [comment]
This should be working now.

**Comment by DamirPorobic** [comment]
Done.
