### ISSUE TITLE
Add Pixelate image area tool

### ISSUE THREAD

**Issue by kpcee** [ksnip/kImageAnnotator#140]
KSnip has the Blur function to blur or soften areas. Another often used function is pixelation. I would be happy if this could be added as well. 

The code for this is also very simple:
```
QImage ImageBlurrer::blurred( const QImage &image, int Counter )
{
    int intensity = Counter * 10;   // 1-25
    auto result   = image.convertToFormat( QImage::Format_ARGB32_Premultiplied );

    result = result.scaledToWidth( image.width() * ( 0.001 * intensity ), Qt::FastTransformation );
    result = result.scaledToWidth( image.width(), Qt::FastTransformation );

    return result;
}
```

Assuming the variable Counter can take values between 1 and 25. Then the result in KSnip would look like this. Above, the original image, the second processed with a value of 20 and the last processed with a value of 5.

![Unbenannt](https://user-images.githubusercontent.com/39984895/90028160-9f6cf580-dcb9-11ea-9ce0-898539619ee3.png)

**Comment by DamirPorobic** [comment]
That's very nice, I like that. As you have the code there, could you provide a PR? I think it would best for it to be a separate tool so there might be a bit more to do.

**Comment by kpcee** [comment]
Yeah, okay, I can look at it, but it's going to take a while.

**Comment by DamirPorobic** [comment]
okey, I'll try to implement that quickly today.

**Comment by DamirPorobic** [comment]
Any idea for a good icon?

**Comment by DamirPorobic** [comment]
I had that in mind but all our icons so far are only single color and we need a light and dark version.

**Comment by kpcee** [comment]
How about a grid like the one shown [here](https://www.flaticon.com/free-icon/pixels_923137) or [here](https://www.flaticon.com/free-icon/grid_589372), there is one in light and one in dark.

**Comment by DamirPorobic** [comment]
The second one might work. I'm working on this feature right now.

**Comment by DamirPorobic** [comment]
Done. Thanks again for providing the functionality.

**Comment by kpcee** [comment]
Thanks!
