### ISSUE TITLE
Icons are not color-scheme-aware

### ISSUE THREAD

**Issue by Pointedstick** [ksnip/kImageAnnotator#141]
We just integrated kImageAnnotator into Spectacle! We are noticing that when using a dark color scheme, the icons do not change color: 

![photo_2020-09-02_11-50-29](https://user-images.githubusercontent.com/1097249/92018541-8254a100-ed12-11ea-9c88-e39fc8d95eb2.jpg)

This is Spectacle with the Breeze Dark color scheme.

**Comment by DamirPorobic** [comment]
That's strange, we do actually support dark and light color schema.

The class responsible for loading either light or dark icons is `src/common/helper/IconLoader.cpp`, could you check if the ThemeLuma is calculated incorrectly?

**Comment by DamirPorobic** [comment]
This seems to be orking for me in the annotator example: 

![image](https://user-images.githubusercontent.com/12796236/104835138-c0f38e00-58a4-11eb-8376-19c911fea16f.png)

and implemented in ksnip:

![image](https://user-images.githubusercontent.com/12796236/104835152-e6809780-58a4-11eb-8846-f8f9a7cc06a0.png)

I'm using OpenSUSE 15.2 with Plasma:
![image](https://user-images.githubusercontent.com/12796236/104835182-247dbb80-58a5-11eb-9fde-73bd15773e55.png)

and Breeze Dark Theme selected:
![image](https://user-images.githubusercontent.com/12796236/104835198-48410180-58a5-11eb-9fb3-56933d89309f.png)

**Comment by precla** [comment]
@Pointedstick can't reproduce it. Works fine in Spectacle. You still have this bug?

**Comment by Pointedstick** [comment]
Nope, seems to be working in Spectacle now. Closing! Sorry for the noise.
