### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [ksnip/kImageAnnotator#147]
hosted.weblate.org/projects/kimageannotator/kimageannotator/#information
is LGPLv3-only

https://github.com/ksnip/kImageAnnotator/blob/master/LICENSE
and for example https://github.com/ksnip/kImageAnnotator/blob/master/src/backend/Config.cpp
is LGPLv3+

It can be changed in https://hosted.weblate.org/settings/kImageAnnotator/kImageAnnotator/#basic

**Comment by DamirPorobic** [comment]
I've changed it in weblate to LGPLv3+. Thanks for letting me know.
