### ISSUE TITLE
Text No Border and No Fill shows shadow beneath text

### ISSUE THREAD

**Issue by derei** [ksnip/kImageAnnotator#148]
When text has No Border and No Fill selected, the box is still casting shadow under the text. It appears like a gray transparent rectangle behind the text.

Also the menu options for the border is not wide enough to accommodate the whole length of the text.

**Comment by DamirPorobic** [comment]
This is actually a workaround for this issue https://github.com/ksnip/kImageAnnotator/issues/70, the cursor is not visible on Linux, it's a Qt Bug. As soon as Qt fixes the issue, we will remove the background. Now thinking about it, the is maybe something that can be done, we just need this background when writing text, after finishing editing, we can hide it. 

Can you log a new issue for the second part regarding the length of text? Also, what OS are you using and what version of ksnip?

**Comment by DamirPorobic** [comment]
Should be now visible only in editing mode, hope this makes it less of an issue. Check out latest ksnip continuous build.
