### ISSUE TITLE
Please consider fit to window for large screenshots

### ISSUE THREAD

**Issue by derei** [ksnip/kImageAnnotator#149]
I observed there is no function to zoom out or fit to window a large screenshot (a whole screen, for example). This makes it a bit inconvenient.Some zooming features would be handy even if is keeping Ctrl pressed when using the scroll wheel.

And perhaps would be a good idea to add two buttons under the color samples in the editor (1:1 and "fit window"), in order to help with the scroll zooming.

**Comment by DamirPorobic** [comment]
For the zoom out there was just a new feature request #150
