### ISSUE TITLE
Zoom out less than 100%

### ISSUE THREAD

**Issue by hgj44d** [ksnip/kImageAnnotator#150]
It would be awesome if it's possible to zoom out less than 100%, for example 80%.

Use case: When I open an image which has a higher resolution than my screen (for example a picture taken with my camera) and I want to edit it with ksnip it's always to big and I can't zoom out to see the whole picture:

![Screenshot_20201012_115102](https://user-images.githubusercontent.com/72733918/95732667-59b0b700-0c81-11eb-815d-8067f24d2a99.png)

**Comment by DamirPorobic** [comment]
Yes, valid request. I'll plan it for the next release.

**Comment by DamirPorobic** [comment]
Implemented, with latest `1.8.0`.
