### ISSUE TITLE
Add numeric pointer with arrow annotation item

### ISSUE THREAD

**Issue by RafaelLinux** [ksnip/kImageAnnotator#152]
I suggested here (with captures) to implement "circle" number adding a "pointer". When I did it, my idea was to put an arrow as "pointer". I can see you implemented the feature (thank you!!) but not just as an "arrow" pointer, but a sizable "triangle". The issue with this way is when user capture text and must point to some areas or words without overlapping other content, is difficult, cause the "stroke" increased his size as far as user drag the pointer.

It is only a suggestion, cause I can imagine the lot of work to do it as it's implemented now.

Thank you anyway

**Comment by DamirPorobic** [comment]
You are thinking about resizing the pointer? That's difficult to implement at the moment as the point is currently not a shape of its own. What could be done is adding a new pointer type with arrow as a pointer instead of the triangle. That might be thinner and better to pointing to something over a larger distance.

**Comment by RafaelLinux** [comment]
Not really to resize, but to avoid the pointer base grow up when the object we want to point is far, should be better to have an arrow (-->) not only the arrowhead (>).

**Comment by DamirPorobic** [comment]
Should be simple to implement.

**Comment by DamirPorobic** [comment]
There you go, available in latest `1.8.0`

![image](https://user-images.githubusercontent.com/12796236/97499992-1d62a380-196f-11eb-9489-3d57ccc267d6.png)

**Comment by RafaelLinux** [comment]
And then background circle dissapear?  :(    
IMHO with a circle background it does more visible and easy to distinguish screenshot from inserted elements.
