### ISSUE TITLE
Move current zoom text to left side config panel

### ISSUE THREAD

**Issue by DamirPorobic** [ksnip/kImageAnnotator#157]
Currently we show the zoom level on the scene but when the whole scene is covered by an image, the text becomes unreadable. A better place might be the bottom of the left side config panel in a read only spinbox.

**Comment by fnkabit** [comment]
@DamirPorobic Do we want a spinbox here ?
It looks a bit odd in my opinion.

![image](https://user-images.githubusercontent.com/73212737/99148424-374ef680-2690-11eb-87ea-734c0c2491e7.png)

**Comment by DamirPorobic** [comment]
I'm open for suggestion but I think it needs to be moved from where it's currently, it's not a good place because when there is text it becomes unreadable.
