### ISSUE TITLE
Annotator "forgets" tool after e.g. drawing an item

### ISSUE THREAD

**Issue by pascal-niklaus** [ksnip/kImageAnnotator#160]
I just upgraded ksnip to 1.8.0 from GitHub and compiled from source.

Now the tool I select is not "permanent". For example, after typing "P" for the pen tool and drawing a line, I am back to the selection tool. This is inconvenient when drawing several items (e.g. handwriting). 

I am not sure whether this is a "feature". If it is, then I'd appreciate an option to disable it.

**Comment by fnkabit** [comment]
> It's actually a feature that was implemented yesterday, I find it more convenient as I always (or often) adjust the tool that I have drawn. I thought already that some users might not like it. The issue is #155
> 
> @fnkabit what do you think, should we make it a config option so that users can decide if they want this or the previous behavior.

I agree, this should be a config option. Will make a PR today.

**Comment by DamirPorobic** [comment]
hmm, I think the "When is this happening" is missing. How about 'Switch to Select Tool after drawing Item'. And yes, default False seems the right choice.

**Comment by fnkabit** [comment]
> hmm, I think the "When is this happening" is missing. How about 'Switch to Select Tool after drawing Item'. And yes, default False seems the right choice.

OK, thank you :)

**Comment by DamirPorobic** [comment]
Merged.

@pascal-niklaus this is now back to the old behavior and the new behavior can be enabled in config.
