### ISSUE TITLE
Brazilian Portuguese translation not loaded

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#176]
Incomplete Brazilian Portuguese translation in both ksnip and kimage annotator

See the example below Ksnip - comparing on the weblate site, the German translation has 291 texts and the Brazilian translation only 243
<a href="https://ibb.co/vH4z0mj"><img src="https://i.ibb.co/SPwvF03/ksnip-20201213-171556.png" alt="ksnip-20201213-171556" border="0"></a>

------------

in kImageAnnotator the same thing in German has 65 texts and in pt-BR only 55 texts
<a href="https://ibb.co/GMvKZ0W"><img src="https://i.ibb.co/KsjMtX2/ksnip-20201213-173119.png" alt="ksnip-20201213-173119" border="0"></a>

**Comment by DamirPorobic** [comment]
The translation files will be updated now with the other files.

**Comment by DamirPorobic** [comment]
Translations should be now up-to-date and brazilian should also be loaded correctly.
