### ISSUE TITLE
Can you turn off Drop Shadow on Text?

### ISSUE THREAD

**Issue by kendoori** [ksnip/kImageAnnotator#179]
I would prefer to not have text default to drop shadow. Is there a way to do that?

Also, is there a way to set default preferences on tools? For example, I would like for text to default to a color and not have a border.

**Comment by DamirPorobic** [comment]
You would like to have no drop shadow for text but for other items you would like to have it? Currently it's the same config for all items, we could split it to be per tool. 

Regarding the config, the defaults are currently hard coded, you can save the config and it will be loaded on next startup, but that's probably not what you're looking for? What could be implemented is some kind of "use current config as default" and then you disable the saving settings and it could use that last config as default. Can you log a new issue this second part?

**Comment by kendoori** [comment]
@DamirPorobic I think it would be best to implement the ability to turn off drop shadow (effects) per tool. In version 1.8, I have no effect selected, and text still shows a drop shadow, so perhaps this is a bug.

I did a short screen cast to show you what I'm experiencing. Am running this on Linux Mint 20 Cinnamon

I will push the other question to a new issue.

**Comment by DamirPorobic** [comment]
The Image Effects refers to the underlying image, not the tools, sorry for the misunderstanding. The drop shadow of tools can be disabled in `Settings > Annotator > Paint Item Shadows` but it's a global settings that will disable shadows for all items.

**Comment by kendoori** [comment]
Great that clarifies usage for me.
