### ISSUE TITLE
Add keyboard shortcut support for text tool

### ISSUE THREAD

**Issue by MurzNN** [ksnip/kImageAnnotator#183]
At now in Text tool the Home-End to quickly jump at start/end of text is not working. Also Ctrl+arrow keys to jump between words not working too. Is it isn't so hard, can you make them working?
Also when I press Right arrow at end of line - cursor jumps to start of text, will be good to fix this too.

**Comment by DamirPorobic** [comment]
Good point. The last is actually a feature, you would expect the cursor to not move anywhere when at end and you press right arrow?

**Comment by MurzNN** [comment]
> Good point. The last is actually a feature, you would expect the cursor to not move anywhere when at end and you press right arrow?

I think yes, that's very strange that it jumps to start, especially when it becomes invisible, like described in #184.

**Comment by fnkabit** [comment]
@DamirPorobic I would like to work on this one please.

**Comment by DamirPorobic** [comment]
This has been implemented. Kudos to @fnkabit.
I have also disabled the jumping cursor from end to start and the other way around.
