### ISSUE TITLE
Cursor in Text tool have too bad visibility

### ISSUE THREAD

**Issue by MurzNN** [ksnip/kImageAnnotator#184]
Current cursor in Text tool have too bad visibility when typing text, for me it have white color with too muted shadow, so it's hard to see it when moving back using arrow keys. And sometimes it is not visible at all! 
Can you make it more visible? Thanks!

**Comment by DamirPorobic** [comment]
This is actually a Qt bug that I have reported in February of this year (2020) and still nothing from Qt side https://bugreports.qt.io/browse/QTBUG-82022

**Comment by DamirPorobic** [comment]
A workaround seems to be to draw some background, which we're already doing in case you've noticed that the background gets a little bit whiter while writing text. We could try making it less transparent, that might improve the visibility.

**Comment by MurzNN** [comment]
Here is increased screenshot of current cursor:
![image](https://user-images.githubusercontent.com/336662/103029679-5bdd9e80-456b-11eb-9851-e55a7ecd1455.png)

**Comment by MurzNN** [comment]
> A workaround seems to be to draw some background

Yes, this is a good workaround, if in edit mode the textbox will have a white non-transparent background.

**Comment by DamirPorobic** [comment]
@MurzNN can you just quickly try to disable the item shadow and check if the cursor is still hard to see?

**Comment by MurzNN** [comment]
Please describe how can I disable item shadow for texts? When I select "Effect = No Effect" in Text tool before adding text rectangle, text still added with shadow :thinking: 
When I try to select the text item after via Select tool, and change effect - the changes applied to image, instead of selected object.

**Comment by DamirPorobic** [comment]
You can enable and disable shadow for items in the Settings (`Settings > Annotator > Paint Item Shadow`). But I'm quite positive that the shadow is causing this issue.

**Comment by DamirPorobic** [comment]
I have lowered the alpha for the drawn background and I've added some functionality to not draw this background when shadow is disabled, I think that this could work for now until Qt fixes the real issue. You might check tonight for new version which includes those changes.

**Comment by MurzNN** [comment]
When disabling shadows - cursor becomes visible:
![image](https://user-images.githubusercontent.com/336662/103095205-da404c00-4610-11eb-85bf-54fae90bbecf.png)
But it have too large width, I think that 1px width will be enough.

**Comment by MurzNN** [comment]
Also it's little confusing, that cursor isn't shows immediately when entering into edit mode, but starts blinking after timeout, also sometimes hides after moving left-right via arrow keys. Maybe you can find quick fix for this too?

**Comment by DamirPorobic** [comment]
The thickness is caused by some logic that prevents blurry drawing for odd width, I might loon into that later on but at the moment it's low prio and not as simple to fix.

I have changed it not to be visible right away and reduced the tick interval from 1000ms to 800ms.

**Comment by MurzNN** [comment]
> You might check tonight for new version which includes those changes.
That's strange, that last continuous build miss `.deb` and other regular builds:
![image](https://user-images.githubusercontent.com/336662/103122033-b53eee00-468f-11eb-9de2-759400b47078.png)

**Comment by MurzNN** [comment]
> You might check tonight for new version which includes those changes.

I checked, now works much better - thanks!
