### ISSUE TITLE
bumped SONAME without name change

### ISSUE THREAD

**Issue by idamir** [ksnip/kImageAnnotator#185]
Origin issue is described here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977649

Spectacle from KDE is unable to start after the libkimageannotator0 package updated to 0.4.0-1
When attempting to start it, it crashes with "error while loading shared libraries: libkImageAnnotator.so.0.3.2: cannot open shared object file: No such file or directory". The problem is that the new version of kimageannotator bumps
the SONAME of the shared library from libkImageAnnotator.so.0.3.2 to libkImageAnnotator.so.0.4.0. This also means that kimageannotator sets the SONAME of its shared library to the full version number, basically breaking compatibility even in patch releases.

Please set correct soname for the library:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -80,7 +80,8 @@ set_target_properties(kImageAnnotator
                                          ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib
                                          LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib
                                          RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/bin
-                                         SOVERSION ${PROJECT_VERSION}
+                                         VERSION ${PROJECT_VERSION}
+                                         SOVERSION 0
                                          )

 install(TARGETS kImageAnnotator
```

**Comment by DamirPorobic** [comment]
I was not aware of this, those library/cmake stuff is not my strong side. Will fix tomorrow for the next version, which is 0.4.1 and should be released next month. 

Why should we set the SOVERSION to 0?

**Comment by idamir** [comment]
SOVERSION is equal to major version of a library.
For example, the 0.4.1 version is: major=0, minor=4? patch_level=1.

**Comment by DamirPorobic** [comment]
Done.

**Comment by antonio-rojas** [comment]
> Usually SOVERSION is equal to major version of a library.
> For example, the 0.4.1 version is: major=0, minor=4? patch_level=1.

Note that this is only the case if your project follows semantic versioning (and, in particular, you don't make ABI-breaking changes between minor releases). The soversion should be bumped whenever there are backwards-incompatible ABI/API changes, regardless of the version number.

**Comment by DamirPorobic** [comment]
> Note that this is only the case if your project follows semantic versioning (and, in particular, you don't make ABI-breaking changes between minor releases). The soversion should be bumped whenever there are backwards-incompatible ABI/API changes, regardless of the version number.

Patch and minor versions should be always backward compatible and not break any code. In case of an interface change that is not backward compatible (removing a method for example) we would provide a major version release for such a change. 

I'm not sure if we're supposed to do here anything? I would prefer avoiding any manual modification of the cmake file for release.
