### ISSUE TITLE
Entering multiple characters at once moves the text cursor only for one character

### ISSUE THREAD

**Issue by grassvalley** [ksnip/kImageAnnotator#186]
中文输入通常会一次性输入多个字符到文本工具。这个时候，文本光标只向右移动一个字符，而不是移动到这次输入的多个字符的最后面。
非常抱歉，英文水平有限，无法用英文描述这个问题。

**Comment by wangzk** [comment]
I meet the same bug in Ksnip. When I used the textbox in the annotation tool, I cannot input chinese characters properly. During typing, the cursor in the text box always automatically went back. However, when I copied a piece of text from another location, there was no such problem.
I have attached a video to demonstrate the bug.

STEPS TO REPRODUCE
1. Take a screen shot.
2. Open the annotation tool.
3. Add a text box.
4. Type "你好" with a Chinese input method in the text box.

OBSERVED RESULT

When I typed "你好[space]"，the cursor went back between "你" and "好" as "你|好".

EXPECTED RESULT

The cursor should appear after the character "好" (i.e., "你好|").

https://user-images.githubusercontent.com/2674020/103458081-ae734380-4d3f-11eb-91e0-ecc55dd4cd33.mp4

**Comment by DamirPorobic** [comment]
@wangzk thanks for the video. Yes, I see the issue in the code, one additional question though, can you delete one of those characters on it's own (I mean in other text editors) or are they also deleted as a group?

**Comment by DamirPorobic** [comment]
Thinking again about it, might be a stupid question, it's a character, you should be able to delete it.

**Comment by wangzk** [comment]
> Thinking again about it, might be a stupid question, it's a character, you should be able to delete it.

Yes, I could delete or move the cursor between Chinese characters one by one.

Thank you for investigating the bug :)

**Comment by DamirPorobic** [comment]
This should be fixed now. You can test it with the continuous build version though it might take up to 50 min for the CI to build it.

**Comment by wangzk** [comment]
I try the nightly build and the bug is fixed. Thank you :)
