### ISSUE TITLE
Translations at Weblate

### ISSUE THREAD

**Issue by milotype** [ksnip/kImageAnnotator#188]
Please check/update the translation files at Weblate. 
Croatian seems to have only 55 strings, while other languages have 66.
English even seems to have 73!

**Comment by DamirPorobic** [comment]
Thanks for letting me know, I'll update as soon as I'm done with a feature that I'm working at the moment. Should be during the day.

**Comment by DamirPorobic** [comment]
Should be now up-to-date.
