### ISSUE TITLE
Zoom in and out with keyboard shortcuts

### ISSUE THREAD

**Issue by DamirPorobic** [ksnip/kImageAnnotator#192]
Currently we support zoom in and out only with mouse wheel, some users don't have one, it might be useful to have a keyboard shortcut for that. For Example `CTRL`+`-` and `CTRL`+`+`

**Comment by DamirPorobic** [comment]
@fnkabit do you have time to look into this? Also, we probably should think about logging another issue for enabling editing that percentage value in the spinbox.

**Comment by grahamperrin** [comment]
Thank you! 

To avoid ambiguity: will the _zoom in_ shortcut be, effectively, two keys?

<kbd>Control</kbd>-<kbd>=</kbd>

– **not** a three-key chord including <kbd>Shift</kbd>

----

I'm comparing with (for example) the menu representation in Firefox 84.0.1 on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/103476917-95a37600-4db1-11eb-99b9-88815239c475.png)

@DamirPorobic your opening post here seems consistent with that ☑ 

(Just rarely, I see `+` interpreted as requiring the <kbd>Shift</kbd> key. It does require that key, _but not_ in the context of this issue.)

**Comment by fnkabit** [comment]
@DamirPorobic I will implement this. Thanks!

**Comment by DamirPorobic** [comment]
Kudos to @fnkabit for implementing this. @grahamperrin  no shift required, just the `CTRL` and `+` or `-`

**Comment by DamirPorobic** [comment]
@grahamperrin I have also added buttons in the UI for zooming in and out:

![image](https://user-images.githubusercontent.com/12796236/104123516-ebe15d80-534b-11eb-9397-ba96d62a212a.png)

**Comment by grahamperrin** [comment]
Thanks, I look forward to the port to FreeBSD https://www.freshports.org/graphics/ksnip/ gaining the enhancements!

**Comment by adnanpmi** [comment]
> @grahamperrin I have also added buttons in the UI for zooming in and out:
> 
> ![image](https://user-images.githubusercontent.com/12796236/104123516-ebe15d80-534b-11eb-9397-ba96d62a212a.png)

which version of ksnip is this?
i'm using 1.8 version in UBUNTU and have hard time zooming in and out with my touchpad and mouse. 
<Ctrl> + <+> for zooming in 
<Ctrl> + <-> for zooming out not working
also there isn't buttons in Zoom panel

please help.

**Comment by DamirPorobic** [comment]
@adnanpmi version `1.9.0` which is still work in progress. If your pain is big, you can try out the continuous build of `1.9.0`, there should be already a lot of new features and fixes that you don't have.
