### ISSUE TITLE
Activating context menu while drawing item leaves item in error state

### ISSUE THREAD

**Issue by RafaelLinux** [ksnip/kImageAnnotator#196]
I'm using my new left hand trackball. I have my mouse button switched, so some times accidentally I press "right-click" plus "left-click" simultaneously. I put "Number arrow" elements here and there, but sometimes, if I press both mouse buttons together , it put the "number arrow" element and seems all is normal. However, how you can see in shared video, if I try to modify or simply click in some areas of captured screen, the arrow of the "number arrow" that I put clicking both mouse buttons simultaneosly, changes its position. It's better to see the video than try to understand my explanation in English.

The effect can be repeated within Spectacle and in KSnip 1.8.0.

https://www.transfernow.net/4fohPs012021

Note: I'm using linux, so I usually only can create open video formats, like WebM. Please, ask GitHub to let upload WebM videos too, cause this 4MB WebM shared video grow to 75MB after I tried to convert to MP4 (and moreover, I can't convert to MOV, the other admitted format). 

Thank you

**Comment by DamirPorobic** [comment]
Thanks for reporting, the video is enough for now. We'll look into it.

**Comment by RafaelLinux** [comment]
Thank you for your great application  ;)

**Comment by DamirPorobic** [comment]
This should be fixed now.
