### ISSUE TITLE
CTRL + A does not select all text typed

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#198]
ksnip 1.9

In the text tool:
Keyboard shortcut CTRL + A does not select all text typed. Draw a strange character.

both on windows and linux

**Comment by DamirPorobic** [comment]
Probably related to this one https://github.com/ksnip/kImageAnnotator/issues/183

**Comment by carloscadux** [comment]
Hi,

I'm using ksnip build 1-1ccc20b on Windows 11.

Currently, it seems there is no effect when pressing common keystrokes for text selection, like:
`ctrl+A`
`shift+arrows`
`shift+end`
`shift+home`

I'd like to suggest the text selection by using those keyboard shortcuts.

The suggestion is illustrated in this screen-recording (https://tinyurl.com/y6yuss54).

Thanks,
Carlos

**Comment by DamirPorobic** [comment]
Can you please test again, the Text Annotation Tool has been reimplemented.

**Comment by antrrax** [comment]
I tested the .deb version on linux mint cinnamon x64 X11

Now behavior is as expected, Ctrl+a : selects all text

Windows version is not available for testing.

**Comment by DamirPorobic** [comment]
I've uploaded the windows builds manually, the automatic upload seems to be broken at the moment, need to fix it.

**Comment by antrrax** [comment]
I test zip version on windows 10 and appimage on linux and they are also working as expected for this functionality

**Comment by DamirPorobic** [comment]
Awesome, thanks for confirming!
