### ISSUE TITLE
Unsupported default font for numbering tool used

### ISSUE THREAD

**Issue by amenk** [ksnip/kImageAnnotator#200]
On Ubuntu 20.04, deb installation (I believe the snap did not have this issue) different fonts are used for Number and Number Pointer

![image](https://user-images.githubusercontent.com/1087128/105160080-197a9380-5b10-11eb-9b72-c12eb5954c31.png)

Maybe some font is missing from my system? Which font is used? I did not find an option to change the font.

**Comment by DamirPorobic** [comment]
Strange, they should have the same. Could you just give it a try with the AppImage?

**Comment by DamirPorobic** [comment]
I'll double check tonight in the code if we really use the same but it should be.

**Comment by DamirPorobic** [comment]
Font Type is "Comic Sans MS" I believe and you can change it from `Options > Settings > Annotation > Numbering Font` but still strange that you have there different entries. Just checked the code, the config seems to be using the same. 

Do you still see something different when you change the font?

**Comment by DamirPorobic** [comment]
hehe I knew that this one would come :D
I thought it looked ok on the numbering tool :)

Any idea what font might be everywhere available?

**Comment by amenk** [comment]
I guess in the end if the day, no font is available everywhere..option could be a fallback for similar looking fonts like it's done in CSS usually with Arial, Open Sans, ...
We can as well just install Comic Sans MS on Linux.
Our goal is to have all screenshots looking consistent across the different platforms in the company.

**Comment by DamirPorobic** [comment]
Comic Sans MS was probably not the best choice. I'll check for an alternative that is more common. Fallback might as well be a good option to have.

**Comment by DamirPorobic** [comment]
Just had a look into the Qt Docu for fonts, it looks like Qt is already trying to find some alternatives that are a close match if no matching font is found on the OS. Maybe just the stupid Comic Sans MS was to much off. How about trying Helvetica or something like that as default and you check what you get on a clean machine?

**Comment by DamirPorobic** [comment]
Ok, changed the default to Arial, which is the same for the text tool.

**Comment by DamirPorobic** [comment]
I'm closing this issue now, if you still have problems with the font we will open a new one and investigate.
