### ISSUE TITLE
Change drop shadow to cover all sites

### ISSUE THREAD

**Issue by pkoerner81929** [ksnip/kImageAnnotator#202]
Applying drop shadows on light/white images is too soft/light. Borders are almost invisible, so placing these captures on white background (paper) looks irritating.

Screenshot 1: left (ksnip), right (other drop shadow filter)
Screenshot 2: ksnip github dropshadow version (nice).

![grafik](https://user-images.githubusercontent.com/17785334/105864854-a59a2880-5ff2-11eb-91a0-de872fe12834.png)

![grafik](https://user-images.githubusercontent.com/17785334/105864919-b480db00-5ff2-11eb-8194-8266bdb76230.png)

**Comment by DamirPorobic** [comment]
I'll see what I can do.

**Comment by DamirPorobic** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/12796236/107088353-216b5080-67fd-11eb-9415-8bde47e4b5b0.png)

**Comment by DamirPorobic** [comment]
@pkoerner81929 how does this look?

**Comment by pkoerner81929** [comment]
Looks good. Should also work with white/gray on white etc.

**Comment by DamirPorobic** [comment]
I'll tr to bring this change into the next `1.8.2` patch which will come very soon I think.

**Comment by DamirPorobic** [comment]
Done, you can check it out in the continuous build.
