### ISSUE TITLE
modify canvas handling is not intuitive 

### ISSUE THREAD

**Issue by c33s** [ksnip/kImageAnnotator#205]
~~sometimes it worked after applying it a few times.~~

edit: removed the first gif and exchanged it with the new one (behavior record of the first image is also in this one

![8UKSwotCCe](https://user-images.githubusercontent.com/649209/106123650-7bfc1100-615a-11eb-9094-5c13bfef9334.gif)

1. try via apply:  i would assume that when i am in "modify canvas" mode, i change the canvas and click apply the canvas gets modified which does not happen
2. try crop toolbar icon: if i assume that "apply" is quite the same as the "cancel" button then i assume that the crop button crops but it is only "launching the crop mode" and sadly also forgetting the selected crop area
3. try after gone in "crop" mode via icon: of course this is the users fault but after being in crop mode it can happen that the user presses the crop "action" again to crop the image but it simply exits the crop mode
4. try in crop mode with the crop text button: the real workflow is "modify canvas" > enter crop mode with "crop" button > select area to crop > go down to the "crop" button which exchanged place with the "apply" button and press it to really crop.

photoshop UX

![kfkhtsaFF9](https://user-images.githubusercontent.com/649209/106129279-64278b80-6160-11eb-95a4-6589fc77c3af.gif)

**Comment by DamirPorobic** [comment]
Thanks for reporting, I know where this comes from.

**Comment by DamirPorobic** [comment]
Just to clarify, the inconsistency is that the canvas changes back to the initial size?

**Comment by c33s** [comment]
> Just to clarify, the inconsistency is that the canvas changes back to the initial size?

i edited my description. please have a look

**Comment by DamirPorobic** [comment]
1. Crop and ModifyCanvas are two different tool
2. The Crop tool is used to make the image smaller, to cut some regions out of the background image.
3. ModifyCanvas is used to change the region (and background fill color) that is going to be exported when you save the image. You would usually use this if you want to export a larger portion of the annotation area then the image, for example if you want draw outside the image. 
4. What you are doing there in the gif is actually switching between the ModifyCanvas tool and the Crop tool, they look very similar but have different functionality. Clicking on crop while the modify tool is open actually closes the ModifyCanvas tool and opens the Crop tool. 

Try drawing an arrow from the image to an outside region (the white region) then try opening opening the ModifyCanvas tool, note the region, then close it via cancel and open the crop tool, you should see that the regions are not same.

**Comment by c33s** [comment]
quite confusing. from my perspective crop and modifycanvas should be the same. for me it is really counter intutive, if i want to interact with the canvas it does not matter if it gets larger or smaller. photoshop had never to explain their crop tool to me. 
it is so easy to do this in PS, nothing to think about, nothing to choose between, just interacting with the canvas of the image.

hopfully i will get used to it. still i would vote for a PS like behavior as i don't really see a benefit from spliting this functionality (except that i can change the crop of the image later after i added a canvas but most of the time i have a non-quad logo where i resize the canvas to be quadratic on transparent background).

**Comment by DamirPorobic** [comment]
Initially I started implementing it just like the PS does it but then I found it very confusing that I have an image, say 100x100, I go in there, crop it to 50x50 then I go back to it again an change the size to 100x100 back but the image stays at 50x50 size, just the canvas is larger now. 

If you want to "crop" with the modify canvas, you can do it, in the example above you decrease the size from 100x100 to 50x50, the image is still there in its original size but if you would save it (or copy to clipboard) only your selected canvas of 50x50 is being exported. 

If you have a use case where you want a 100x100 image to be cropped to 50x50 and then export this 50x50 image within a 100x100 transparent region, even in PS you would have to do it twice, first open the crop tool to crop it down, confirm, then open the crop tool again, extend and confirm again. 

For me crop is a permanent operation on the image while modifying the canvas is kind of "adjusting" the region below the image.  

I'm not trying to sell you my solution, it's generally a bad sign if you have to explain your UI to someone (except expert systems) I'm just telling you what my logic is behind it was. When this feature was initially requested one of the users gave PS as example, that's why I started implementing it but as I'm not a PS user, I found that solution not very intuitive, at least I was confused by it. When a lot of users find my solution confusing then maybe I need to refactor it and mimic the PS way of doing.

**Comment by c33s** [comment]
>have an image, say 100x100, I go in there, crop it to 50x50 then I go back to it again an change the size to 100x100 back but the image stays at 50x50 size, just the canvas is larger now.

would be the exact function i am looking for :)

in photoshop you have the checkbox "delete pixel" in the crop tool. if checked and you crop the image 100->50 and then crop-resize it to 50->100 again. you get a 50px image with another 25px transparent canvas "border" around the image. if i check the box before i will get the original pic back.

> even in PS you would have to do it twice

not 100% true:

- click crop tool
- be sure delete croped pixes is checked
- resize the image crop field to be 50x50
- press enter
- resize the still active crop field to 100x100
- press enter
- done.

so photoshop is not chanceling the crop mode after the crop. you select the crop tool and it behaves the same as a pen tool. as long as you don't select a different tool you are in crop mode.  they have the additional canvas size in their menu

![MjCmRZNy30](https://user-images.githubusercontent.com/649209/106181688-2ea19300-619e-11eb-97a9-5cabb1c4b6ae.gif)

i really hate adobe for switching to a subscription model, so photoshop cs6 was the last photoshop i bought and which i still use. again i hate adobe for that but i have to say that their UX/UI designer (photoshop section - don't know that much about the other tools) are brilliant. awesome shortcuts and very good interfaces which need no explanation for core functionalities.

in ksnip the same basic function is "hidden" behind two tools (one as tool button and the other in the menu) was really confusing for me.

for me both is basically the same and modifier keys or checkboxes are quite fine to toggle between different behavior, or a config setting like "photoshop crop tool behavior" or at least the config to have both at the same spot (menu or toolbar).

> I'm not trying to sell you my solution

your are not, you made good software an share it for free. i just try to also be a good OS "member" do software testing and report bugs and suggestions :)

> it's generally a bad sign if you have to explain your UI to someone

funny you wrote that, i wanted to quote martin in my comment

> “A user interface is like a joke. If you have to explain it, it’s not that good”. — Martin Leblanc

> When this feature was initially requested one of the users gave PS as example

that was me :)

to quote myself "software is not hardware or architecture, you don't have to choose if you building should have a flat top or a pitched roof. software can have both" so i always vote for config.

as developer i started with eclipse then switched to netbeans and now i use phpstorm but i still use the eclipse shortcuts...
