### ISSUE TITLE
Translation for annotation icons missing

### ISSUE THREAD

**Issue by gimplyworxs** [ksnip/kImageAnnotator#206]
Hi,
The hints for the editing icons like "arrow" or "blur" on the left hand side 
are not translated. Is there a way to have them translated?
![-ksnip-Ungespeichert_074](https://user-images.githubusercontent.com/59622701/106264109-89320200-6225-11eb-89b3-1b5c4ea7cbfd.png)

**Comment by DamirPorobic** [comment]
Should be doable, need to have a look if I forgot to enable translations there.

**Comment by gimplyworxs** [comment]
Just noticed:  when launching ksnip from commandline I get this message:

> Unable to find any translation files for kImageAnnotator.
Don#t know if it helps with the issue

**Comment by DamirPorobic** [comment]
Definitely, the translation files have not been found. How did you install ksnip?

**Comment by gimplyworxs** [comment]
I used the .deb file
tried both 1.8 and 
Version: 1.9.0-continuous
Build: 1781-ea4d2f9

**Comment by DamirPorobic** [comment]
Ok, that means you're facing this issue here https://github.com/ksnip/ksnip/issues/359

A workaround would be using the AppImage, snap or flatpak.

**Comment by DamirPorobic** [comment]
Closing issue as being duplicate.
