### ISSUE TITLE
Text/Number Pointer and Text/Number Arrow don't inherit Text/Number Font in Settings

### ISSUE THREAD

**Issue by fsevenm** [ksnip/kImageAnnotator#208]
I changed the font in settings but unfortunately it only affects Text, not Text Pointer nor Text Arrow. My expectation was when chaning font in settings, it will affects all Text tools.
![image](https://user-images.githubusercontent.com/29963765/107142391-922f7b80-6969-11eb-820d-8f0c14d900d3.png)

**Comment by DamirPorobic** [comment]
I'll have a look.

**Comment by fsevenm** [comment]
As addition, I am using ksnip 1.8.0 on Ubuntu 18.04 (X11), installed using deb package.

**Comment by DamirPorobic** [comment]
This is fixed now in `1.8.1` and later. Thanks for reporting!

**Comment by fsevenm** [comment]
Great 🎉. Can't wait for that ksnip 1.8.1 release.

**Comment by fsevenm** [comment]
I can confirm now that in 1.8.1 continuous build this issue has been fixed.
![image](https://user-images.githubusercontent.com/29963765/107295555-8e574280-6aaa-11eb-8e24-a535cef935f1.png)
