### ISSUE TITLE
Add zoom in/out capability to crop view

### ISSUE THREAD

**Issue by robertbyers1111** [ksnip/kImageAnnotator#212]
I recently wrote a ksnip review on alternativeto.net in which I described my confusion trying to crop a fullscreen screencap. One feature that might make this type of situation easier for the user would be an ability to zoom in/out in the editor (not scaling the image itself, only changing the window's zoom) (and, furthermore, when the user clicks 'crop' for an image that doesn't fit in the edit window, automatically zoom out so all 8 crop drag points are visible without having to scroll)

This is from my review...
> My biggest complaint was its editor's cropping tool which, for full screen captures, took me a while to figure out. Cropping itself works fine and works similar to most other apps' cropping features. It has eight cropping points that can be dragged to mark the area to crop (just like most crop tools) - top-left, top-middle, top-right, middle-left, middle-right, bottom-left, bottom-middle and bottom-right). But a full-screen capture does not fit in the editor's window, and therefore you don't see five of the eight points (!), they're scrolled off the edges of the editor's window. You must scroll the editor right and down in order to see those drag points.
>
> To further confuse me, often times when I look at the edit window and see a scroll bar I think it is part of the captured image and not an active scroll bar from the editor. So for a long time I didn't even try to scroll right and down, and therefore I had the hardest time figuring out how to crop!
>
> I suppose there are things ksnip could do to make cropping a fullscreen screenshots a little easier (maybe display its own scroll bars in a different color, or maybe default to zoom out when cropping an image that doesn't fit in the editing window)

**Comment by DamirPorobic** [comment]
You should now be able to zoom in the crop view.
