### ISSUE TITLE
Duplicate region of grayscale image has color

### ISSUE THREAD

**Issue by DamirPorobic** [ksnip/kImageAnnotator#213]
I just made the build of ksnip from master just to use this. it is very useful!
I found a small bug only when the Grayscale effect is applied. The part that was duplicated still has colors.

_Originally posted by @fabianski7 in https://github.com/ksnip/kImageAnnotator/issues/165#issuecomment-782747054_

**Comment by fnkabit** [comment]
@DamirPorobic Can I look into this one ?

**Comment by DamirPorobic** [comment]
Sure, I was hoping you will take care of it :)

**Comment by fnkabit** [comment]
Thanks ! Will fix it today.

**Comment by fnkabit** [comment]
@DamirPorobic Do you think there is anything else that needs fixing here ? Thanks !

**Comment by DamirPorobic** [comment]
Haven't had a look at this PR yet, I'll try to do it during the week.

**Comment by DamirPorobic** [comment]
@fabianski7 this should be fixed now. Kudos to @fnkabit for fixing it!
