### ISSUE TITLE
Change text font

### ISSUE THREAD

**Issue by medmedin2014** [ksnip/kImageAnnotator#222]
There is no way to change font in annotation mode. It would be cool to have it as an option.

Operating System: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.4.105-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11

**Comment by DamirPorobic** [comment]
There is a feature request for that already https://github.com/ksnip/kImageAnnotator/issues/130

**Comment by DamirPorobic** [comment]
Closing, duplicate.
