### ISSUE TITLE
Allow disabling item shadow per item from UI

### ISSUE THREAD

**Issue by medmedin2014** [ksnip/kImageAnnotator#223]
In annotation mode when I select "No effect" in any shape or text tool the shadow is always applied and can't be removed.

Operating System: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.4.105-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11

**Comment by DamirPorobic** [comment]
This here applies only effects to the background image
![image](https://user-images.githubusercontent.com/12796236/112661335-b16d6400-8e56-11eb-9cdf-2e0a4715168f.png)

If you want to disable shadows on annotation **items**, go to `Options > Settings > Annotator` and uncheck `Paint Item Shadows`

**Comment by medmedin2014** [comment]
That position of background image's effects is not intuitive at all, because it appears at top of slection item's options, so any user will automatically thinks it concerns the selected item.
And from Spectacle there is no way to access Annotator settings.

**Comment by DamirPorobic** [comment]
I agree, but it's the only position for config that we have. I'm planning some refactoring of the UI, this one will probably get a new position. Maybe the enable/disable shadow checkbox gets also moved into the UI.

**Comment by DamirPorobic** [comment]
@Langlais115 @medmedin2014 this has been implemented now. I need to fix some UI things and I'm still thinking about using different UI button for the selection but it should be work already.

**Comment by DamirPorobic** [comment]
This is implemented now.

**Comment by medmedin2014** [comment]
The news layout looks really good and better than previous one.

**Comment by DamirPorobic** [comment]
Thanks, next I'm going to work on the font setting in the UI https://github.com/ksnip/kImageAnnotator/issues/130
