### ISSUE TITLE
Applying effect on any shape or text not working

### ISSUE THREAD

**Issue by medmedin2014** [ksnip/kImageAnnotator#224]
In annotation mode if I select any shape (arrow, rectangle,...) or text then select an effect like drop shadow or grayscale or border, the effect is applied to background image and not the selected shape or text.

Operating System: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.4.105-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11

**Comment by DamirPorobic** [comment]
Yes, that's because the **Image Effect** applies only to the **Background Image**.

**Comment by medmedin2014** [comment]
The real wanted option is enable/disable shadow for items, while here we have the one for background image, and the wanted one is hidden and can't be accessed from Spectacle.

**Comment by DamirPorobic** [comment]
Mate, the options is there, the Spectacle guys just need to make it accessible to users, we are not involved in Spectacle at all.

**Comment by DamirPorobic** [comment]
Closing this one, also duplicate issue regarding disabling shadow.
