### ISSUE TITLE
Marker shows fill and width config when modifying existing item

### ISSUE THREAD

**Issue by medmedin2014** [ksnip/kImageAnnotator#225]
In annotation mode if I create any marker then change its color it becomes opaque and there is way to change it opacity to be transparent.

Operating System: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.4.105-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11

**Comment by DamirPorobic** [comment]
Yes, that's because the marker, like a marker in real life is transparent so that you can see what is behind it. If you want something that is not transparent you should be using the Pen, which is never transparent.

**Comment by medmedin2014** [comment]
No you didn't understand my problem, what I mean is when you create a marker it appears transparent, then you select it and change its color then it will become opaque and there is no way to make it transparent again.

**Comment by DamirPorobic** [comment]
Ok, that doesn't sound right. This happens with Spectacle? Can you try this with ksnip AppImage? Just tried locally on my PC and it seems to be working. 
![image](https://user-images.githubusercontent.com/12796236/112665981-f34cd900-8e5b-11eb-9a24-7c92195f3228.png)

**Comment by medmedin2014** [comment]
The same happens with ksnip 1.8.2

https://user-images.githubusercontent.com/7027319/112667951-2f813900-8e5e-11eb-9329-d661bcd95679.mp4

**Comment by DamirPorobic** [comment]
Oh, yes, you have the fill setting there, the mark shouldn't have it.

**Comment by DamirPorobic** [comment]
Same for the thickness.

**Comment by DamirPorobic** [comment]
This sould be fixed now, those two configs should not longer be available for hose tools.
