### ISSUE TITLE
Popup menus shown outside screen

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#226]
Tools that have a submenu,
Submenu items are off the screen regardless of the location of the toolbar.

Especially when it is on the bottom or on the right side.
But it also occurs when it is on the left side and is in the lowest position on the screen.

<a href="https://ibb.co/fxmCZLh"><img src="https://i.ibb.co/nLhD4tH/erro.jpg" alt="erro" border="0"></a>

**Comment by DamirPorobic** [comment]
Should be fixed now.
