### ISSUE TITLE
Highlighter/Marker washed out color and overlapping

### ISSUE THREAD

**Issue by stephen322** [ksnip/kImageAnnotator#227]
Using the Marker to highlight text, it appears washed out (not very eye catching) and doesn't seem to match the color picker.
Could it be modified to behave more like a GIMP layer mode "Multiply"?

**Comment by DamirPorobic** [comment]
We'll see what we can do.

**Comment by DamirPorobic** [comment]
This should be fixed now and looks indeed a lot better. Thanks for the tip with multiply, that did the trick.
