### ISSUE TITLE
Select item after drawing it and allow changing settings

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#230]
With this new toolbar concept, when inserting a new item (text, arrow and everything), it should be selected automatically.

As it is today (not selected) if I make any changes to the tool, it is not applied to the current item, only to the next items.
Ex: if I disable the shadow it is not applied to the current item that I just created, only to the next item. So I need to select the item I just inserted to change the shadow just like that.

**Comment by DamirPorobic** [comment]
Yes, but that's the same behavior that we had in the old version. If you add an item, change color, the change is applied to the next item.  

We have currently a config option that switches to select tool after drawing a new item. We could extend it to also select the new item.

**Comment by antrrax** [comment]
In my point of view it would be more intuitive if the new item came already selected

**Comment by DamirPorobic** [comment]
Yes, that's what I mean. I would only make this behavior configurable, somebody might prefer the current behavior.

**Comment by DamirPorobic** [comment]
This is implemented now.
