### ISSUE TITLE
Obfuscation tool shows fonts settings when switching from tool with font

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#231]
When selecting a tool that has a font option and then selecting the obfuscating tool, the font options that do not belong to that tool are also displayed in the toolbar.

When selecting another tool that does not have a font option (arrow), and then selecting the obfuscate tool, only the obfuscation factor option is displayed

<a href="https://ibb.co/rckPNgj"><img src="https://i.ibb.co/BrLDFmp/erro.jpg" alt="erro" border="0"></a>

**Comment by DamirPorobic** [comment]
A bug, will fix it.

**Comment by DamirPorobic** [comment]
Should be fixed now.
