### ISSUE TITLE
Not possible to enter value in the width tool

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#233]
in the font tool it is possible to type the number for the font size.
However, in the width tool it is not possible to type the number directly, I can only use the arrows on the spin button.

I think it would be interesting to add the function of typing the width value in addition to using the up and down arrows on the spin button. It would speed up the action, ex: current width is 10 if I need to change it to 20 I will need to give 10 clicks.

In all tools:
Width 
Obfuscation Factor
Number Seed

**Comment by DamirPorobic** [comment]
I'll have look, it should work everywhere.

Btw. you can also use mouse wheel when the cursor is over the spinbox, just as a side note.

**Comment by DamirPorobic** [comment]
Should be fixed now.
