### ISSUE TITLE
Words overlap when resizing text box

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#234]
Words overlap when resizing text box
It would be best if there was a line break when resizing the text box to a smaller size.

see video (ksnip):
https://www.mediafire.com/file/03o14qpizn5mdez/overlap.mp4/file

see an example of how it works in Libreoffice Impress:
https://www.mediafire.com/file/20wi06up7kq5via/impress.mp4/file

**Comment by DamirPorobic** [comment]
That's a known issue https://github.com/ksnip/kImageAnnotator/issues/211
