### ISSUE TITLE
Cut out vertical or horizontal slice of an image

### ISSUE THREAD

**Issue by Rmano** [ksnip/kImageAnnotator#236]
One of the editing actions I miss more is something that I really do not know how to do rapidly, and it will be very useful, is "zapping away" a vertical or horizontal slice of the image. 

For example, in the following image, I'd like to delete the marked part and then paste the two sides together, maybe leaving a line (or a zig-zag "broken thing" to be fancy) in the middle:

![image](https://user-images.githubusercontent.com/6414907/100088655-c1494d00-2e50-11eb-813f-74e7384aa227.png)

This would be very useful when screenshotting tables (for example, spreadsheets) and you want to remove a group of columns or lines!

**Comment by DamirPorobic** [comment]
This is now implemented.

**Comment by Rmano** [comment]
Tested on today's continuous build, it works like a charm!

**Comment by DamirPorobic** [comment]
Nice :)

**Comment by Rmano** [comment]
I see that it finally is just a plain "cut-out" --- not a big problem because I can add a line after-the-fact to show that something has been cut away. It would be nice if such a line could be added automatically (maybe with an option) --- just adding a dashed line on the cut would do. 
Anyway, it's already a killer feature --- I never saw anything like that on screenshotter and it's really useful. I'll promote it!

**Comment by DamirPorobic** [comment]
Yeah, I had in mind to offer some "fillers" that you can select from, probably "No filler" and "line" could be the starters but didn't have time yet.

**Comment by mendy12** [comment]
Hello, cut works great BTW.
This might be a doable option to insert a break line on the cut screenshot.
Tried zig-zag but did not quite look right. Settled on a break line used in Cad.
Experimented with a shorter version but for some reason the diagonal lines become fatter on resizing so made longer versions and then just have to resize down to screenshot. Made in Inkscape in four lengths and still testing on various screenshots. Also in horizontal versions.

Method:
Add .svg file to stickers. Then click sticker tool and in settings select file then click on cut screenshot. Move into place and shorten legs.
If interested can upload the file.

Attached image shows it seems to be ok in light and dark.

![LD](https://user-images.githubusercontent.com/71085201/181211074-ffcd042f-b07a-4215-8dde-387183719bd7.jpg)

**Comment by mendy12** [comment]
My bad kinda slow did not realize till just now that I was not in a Ksnip posting area but in the kimageAnnotator section, sorry for the intrusion.

**Comment by DamirPorobic** [comment]
This is issue done, lets discuss other changes in seperate issues.
