### ISSUE TITLE
Annotation tools are not displayed if application starts with docks hidden

### ISSUE THREAD

**Issue by fabianski7** [ksnip/kImageAnnotator#237]
**Describe the bug**
It appears that after the changes discussed and made in discussion https://github.com/ksnip/ksnip/discussions/562, the dock is no longer displayed when it is automatically hidden.

Using the TAB key, everything works correctly, as long as the automatic option has not been activated.

**To Reproduce**
1. Build the latest version of ksnip (I'm using the aur git package)
2. Enable the option to auto hide docks
3. Restart the program

**Screenshots**
I tried to show the bug in this video.
Another important thing is that after activating the option to automatically hide the dock and restart ksnip, there is no way to "undo the bug" through the gui. That's because even disabling the hide option is not enough to bring the dock back.
What I had to do was delete the [KImageAnnotator] section of the ksnip.conf file

https://user-images.githubusercontent.com/47755037/117888380-82de0800-b2a1-11eb-9ca5-42d788a94f44.mp4

**Desktop (please complete the following information):**
- KDE Plasma Version: 5.21.5
- KDE Frameworks Version: 5.82.0
- Qt Version: 5.15.2
- Graphics Platform: X11

**Comment by DamirPorobic** [comment]
Good catch, will have a look into it.

**Comment by DamirPorobic** [comment]
Should be fixed now, can you test?

**Comment by fabianski7** [comment]
yes, fixed. thanks!
