### ISSUE TITLE
Not possible to disable tool automatically deselected after drawn

### ISSUE THREAD

**Issue by raphaelh** [ksnip/kImageAnnotator#238]
**Describe the bug**
The selected tool is automatically deselected after being used once. It didn't happen in 1.8.2.

**To Reproduce**
1. Select a tool, for example Rectangle (in red)
2. Use it once

The Rectangle tool (in red) is automatically deselected, and the Select tool (in blue) is automatically selected instead.

So if I want to draw a second rectangle, I have to select it again.

![ksnip-tool-deselected-1](https://user-images.githubusercontent.com/542500/118991074-b563c100-b983-11eb-8a96-6ce95353b8fe.png)

I've deselected this option, but it makes no difference:

![ksnip-tool-deselected-2](https://user-images.githubusercontent.com/542500/118992081-9c0f4480-b984-11eb-884e-fbc8395a15b0.png)

**Expected behavior**
Keep selected tool selected. It used to work in 1.8.2

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution in case of Linux : Ubuntu
 - ksnip version : https://github.com/ksnip/ksnip/releases/download/continuous/ksnip-1.9.0-continuous.deb download 10 minutes ago
 - How did you install ksnip : dpkg

**Comment by DamirPorobic** [comment]
I'll have a look.

**Comment by DamirPorobic** [comment]
Should be fixed now. Disabling it in settings should work now.

**Comment by raphaelh** [comment]
Works perfectly now! Thanks
