### ISSUE TITLE
Annotation tool shortcuts do not work if the panel is hidden

### ISSUE THREAD

**Issue by fabianski7** [ksnip/kImageAnnotator#239]
**To Reproduce**
1. Hide the panel
2. Use some keyboard shortcut to try to activate any annotation tools, such as Text (T)

**Desktop (please complete the following information):**
- KDE Plasma Version: 5.21.90
- KDE Frameworks Version: 5.82.0
- Qt Version: 5.15.2
- Graphics Platform: X11
- Ksnip, kimageannotator and kcolorpicker built from the master today (aur)

**Comment by DamirPorobic** [comment]
This is a regression, right, this was working before?

**Comment by fabianski7** [comment]
I am not sure. I tested version 1.8.2 but it doesn't seem to have this function of hiding the panels

**Comment by DamirPorobic** [comment]
yes, you're right, that is a new feature. I'll have a look.

**Comment by DamirPorobic** [comment]
This should be working now. However, I have introduced a new bug that is IMO less problematic then this one #240 

Can you test?

**Comment by fabianski7** [comment]
yeah, it's working now. thanks.

I don't know if it was something that happened after this "hack" to solve this issue, but it seems to me that the spacing between the edges of the window is misaligned. 
When the panel is hidden, the left margin is larger than the right.

![ksnip_tmp_bpLRgB](https://user-images.githubusercontent.com/47755037/119265845-cd338300-bbd7-11eb-9837-17709cf15991.png)
