### ISSUE TITLE
Crashes on destruction

### ISSUE THREAD

**Issue by tsdgeos** [ksnip/kImageAnnotator#242]
* Run spectacle
* Close spectacle
* Crash

There is too much deleting of widgets and layouts going on, in particular the issue seems to be in FontPicker but there's too many deletes everywhere. In Qt you don't need to delete widgets or layouts to which you have given a parent, the destructor will take care of deleting them, you *can* delete them manually but you have to be careful of not double deleting, i.e if you delete mLayout, that will already delete mButtonLayout because it is it's child `mLayout->addLayout(mButtonLayout)` so when you do later `delete mButtonLayout` again it crashes because you have already deleted it.

My suggestion would be to not do manual deleting of QWidgets and just left the parent/child relationship cleanup everything.

**Comment by DamirPorobic** [comment]
Thanks for reporting, I'll have a look.

**Comment by thrimbor** [comment]
I have a backtrace from the Spectacle crash, in case that helps:
[spectacle-20210529-174329.kcrash.txt](https://github.com/ksnip/kImageAnnotator/files/6564930/spectacle-20210529-174329.kcrash.txt)

**Comment by DamirPorobic** [comment]
Thanks, I'll have a look into this issue tomorrow.

**Comment by eiglow** [comment]
Downstream bug report: https://bugs.kde.org/show_bug.cgi?id=437674

**Comment by DamirPorobic** [comment]
I have removed deletes of widgets and layouts where a parent was provided on construction. Would be nice if someone could test.

**Comment by thrimbor** [comment]
That does seem to have fixed it, Spectacle no longer crashes when closing.

**Comment by DamirPorobic** [comment]
Awesome, version is tagged now.

**Comment by dflogeras** [comment]
I also confirm the spectacle segfault is gone, thanks!
