### ISSUE TITLE
Cropping only works on one image, even if there are others

### ISSUE THREAD

**Issue by fabianski7** [ksnip/kImageAnnotator#249]
To reproduce:

1. Take two screenshots and paste into each other (CTRL+Shift+V)
2. Use the cutting tool

It is only possible to crop the first image, not both as if they were a single image

**Comment by DamirPorobic** [comment]
Yeah, because the pasted image is an annotation item that you can move around, like for example an arrow. Cropping only affects the background image.

**Comment by DamirPorobic** [comment]
I'm closing this issue as it's working as designed.
