### ISSUE TITLE
Crash while typing text on wayland

### ISSUE THREAD

**Issue by luizluca** [ksnip/kImageAnnotator#256]
I reported to kde but they asked me to report here.

https://bugs.kde.org/show_bug.cgi?id=443412

There there is some extra debug/stack from KDE crash handler.
The program crashes as soon as I type the first char. I'm using wayland.

**Comment by DamirPorobic** [comment]
Should be fixed in 0.5.3.

**Comment by luizluca** [comment]
Thanks!
