### ISSUE TITLE
Blur/Pixalate tools are not filling within area properly 

### ISSUE THREAD

**Issue by carloscadux** [ksnip/kImageAnnotator#259]
Hi,
 
Reporting an issue with ksnip v1.10.0 under Win 10 (build 19043), which starts happening after sometime using the Blur/Pixalate tools.
I mean, when you just start a ksnip session, the Blur/Pixalate tools are working properly, but at some point, they won't anymore.
The within area filled by these tools are including content that are out of the selection area.
Please, see this screen-recording detailing the issue: https://bit.ly/3F7mNSs
If you need further information or more testing, just let me know.
 
Cheers,
Carlos

**Comment by DamirPorobic** [comment]
Thanks for reporting. Strange, the offset seems to be the same all the time, could it be that you have done a crop or something on your first tab?

**Comment by carloscadux** [comment]
Indeed, I did a crop in the image which presented the offset problem with the blur/pixalated tool.

As shown in this new screen-recording (https://bit.ly/3wHf22B), I performed (a) further tests using that cropped image, as well as (b) other test using another image in which the blurred rectangles started disappearing after cropping.

Regarding (a) further tests using that cropped image, you will noticed that the offset problem had disappeared, and suddenly it started over. 

About the (b) other test using another image in which the blurred rectangles are disappearing after cropping, you will notice that some of the blurred rectangle "layers" had become invisible. I could select the rectangles, but the blur was "invisible". Tried first to bring them to front, without success. After clicking on the rectangles several times using the select tool, they became blurred again.

So extending the issues with the blur tool: offset and disappearance. Both issues seems related to crop an image.

If you need further information or more testing, just let me know.

**Comment by DamirPorobic** [comment]
I think that's enough for know, I'll get back to you in case I have some question when I start working on this issue.

**Comment by DamirPorobic** [comment]
@carloscadux can you please check if this issue still persists?
