### ISSUE TITLE
Interface window isn't restored to the "default" mini-size anymore after an image is closed with the interface maximized

### ISSUE THREAD

**Issue by carloscadux** [ksnip/kImageAnnotator#261]
Hi. Reporting a possible issue with ksnip v1.10.0 under Win 10 (build 19043), which is detailed in this screen-recording: https://bit.ly/30jrqdz
After maximizing the interface having a loaded image, even after the image is closed and there is no image on the editor, the interface window isn't restored to "default-mini" size anymore. 
If you need further information, just let me know.

**Comment by carloscadux** [comment]
This issue refers to ksnip and I posted it wrongly under kImageAnnotator.
Just referring to the correctly posted issue and closing this thread: https://github.com/ksnip/ksnip/issues/757

**Comment by DamirPorobic** [comment]
Btw I can transfer an issue from one repo to another, just write a comment, so you don't have to recreate it. Just in case you get that situation in future.
