### ISSUE TITLE
Undo/Redo within kImageAnnotator [feature request] [question]

### ISSUE THREAD

**Issue by precla** [ksnip/kImageAnnotator#262]
Would it be ok to add undo and redo within kImageAnnotator? So if it's used within an other program (again, like in Spectacle :) ) one can use the undo redo of it and within the widget size of kImageAnnotator instead of having it outside of it.

**Comment by DamirPorobic** [comment]
Where would you place it? Yeah, that's one thing I wanted to ask, does Spectacle allow to use the advanced options, like Crop, Scaling, Modify Canvas? Ksnip handles this via file menu but in Spectacle it's not available I think? Or maybe have some advanced menu that shows all that stuff that can be hidden.

**Comment by precla** [comment]
Thought about adding to "General settings". Hm, adding it to kImageAnnotator would make it appear twice in Ksnip.

That's what we're discussing here: https://bugs.kde.org/show_bug.cgi?id=429981
Includes an screenshot of how it might look if added to Spectacle. Tho, not final ofc.

Currently:
![2021_11_16_184644](https://user-images.githubusercontent.com/7177449/142038447-7f0c649c-d90b-4e3d-a68f-368e776a6fe8.png)

@Pointedstick

**Comment by DamirPorobic** [comment]
Yeah, that would be kind of an issue for ksnip to have the buttons up there and then again in the annotator as part of the "General" widget. We could add another dockable widget that we can add or remove by config and ksnip just removes it but then again, seems a bit strange placement for those buttons. Usually they're up at the top. 

Would it be an option for Spectacle to add a toolbar above the annotator? There are other buttons that users might would like to use, like already mentioned, crop, scaling, modifying canvas and undo/redo? All those the annotator already can do but they're hidden or unreachable in Spectacle.

**Comment by precla** [comment]
That would be great, to add it as a new widget but hidden by default. Also, having the lower two widgets in the same row as the top widget and squeeze in the additional widget with `crop, scaling, modifying, undo/redo` to save space would be an option or a solution I'd (personally) favor.
Let's see what I can come up with :D

**Comment by DamirPorobic** [comment]
Let's give it a try. Looking forward to see with what you come up ;)
Let me know if you need some input from my side.

**Comment by precla** [comment]
Where did you get the .svg files from?

Working on it atm, heavy draft, no functionality so far:

https://github.com/precla/kImageAnnotator/tree/transformation_selection

**Comment by DamirPorobic** [comment]
I'm a one-man-show, I made them myself, you can probably tell by the poor quality xD

**Comment by precla** [comment]
Ok, just added, lacks one for modify canvas tho. They look good and informative :D

**Comment by precla** [comment]
https://github.com/ksnip/kImageAnnotator/pull/263

**Comment by Pointedstick** [comment]
Yaay!
