### ISSUE TITLE
Blur / Pixelate break when going past image edge once

### ISSUE THREAD

**Issue by Chrismettal** [ksnip/kImageAnnotator#267]
**Describe the bug**

- While dragging "blur" or "pixelate" operation over the edge of an image, the image will extend its canvas, but the blur filter will not expand with it. After this, the filter will only apply to a subset of the dragged rectangle, making it impossible to blur out sections.
- I suspect that extending the canvas while dragging an object out of the current capture expands the canvas in the calculation of the filter, but never shrinks it again if the canvas is not actually expanded because the operation is aborted.

**To Reproduce**

1. New region capture:
![image](https://user-images.githubusercontent.com/39636046/147410111-149f705b-3a79-43e0-8e48-9a351dffab36.png)

2. Example of working filter, dragged pixelation in the dimensions marked red: 
![image](https://user-images.githubusercontent.com/39636046/147410110-df8fdac1-697f-4d43-9bce-8d6a9e832a30.png)

3. Start pixelation filter at A and drag B over the edge of a picture **without releasing the mouse** and then return into the frame, trying to apply the frame as it is marked now. Watch as the filter will only fill part of the rectangle::
![image](https://user-images.githubusercontent.com/39636046/147410181-5a9a3a5c-5aa2-4669-8871-c4ff216bbaa2.png)

4. Try applying a new pixelation filter, even after CTRL-Z reverting all changes in the same capture. Will not work correctly until a new capture is taken (In this case only a small edge got pixelated. Maybe because I expanded the canvas downward while dragging the letter B around):
![image](https://user-images.githubusercontent.com/39636046/147410218-1643a3cb-6c20-4c59-ac36-40f0d6424d35.png)

**Expected behavior**
The pixelation/blur filters always fit the dragged rectangle, no matter if the canvas changed size.

**Desktop (please complete the following information):**
```
                   -`                    chrismettal@MonstArch 
                  .o+`                   --------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: MS-7B77 1.0 
               `+oooooo:                 Kernel: 5.15.11-arch2-1 
               -+oooooo+:                Uptime: 5 hours, 3 mins 
             `/:-:++oooo+:               Packages: 1206 (pacman) 
            `/++++/+++++++:              Shell: bash 5.1.12 
           `/++++++++++++++:             Resolution: 3440x1440 
          `/+++ooooooooooooo/`           DE: Plasma 5.23.4 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: Breeze Light [Plasma], Layan-dark [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], Tela [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: yakuake 
     /ossssssss/        +ssssooo/-       CPU: AMD Ryzen 7 2700X (16) @ 3.700GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce RTX 2080 Ti Rev. A 
  `+sso+:-`                 `.-/+oso:    Memory: 6435MiB / 32112MiB 
 `++:.                           `-/+/

```
 - OS: Linux
 - Distribution in case of Linux: Arch
 - Window System in case of Linux:  X11
 - ksnip version: 1.9.2
 - How did you install ksnip: `pacman -S ksnip`

**Comment by Chrismettal** [comment]
My bad, I didn't notice that kImageAnnotator is a standalone repo with its own issues. Would have commented on one of those instead of opening my own!

**Comment by DamirPorobic** [comment]
Not a problem, transferring and issue is not a big deal. Does and of the two bugs match your issue? Do we have a duplicate or a new issue?

**Comment by Chrismettal** [comment]
They very well could be caused by the same bug. It does look like the overlay image used for the blurring effect is shifted from the underlying image in all 3 examples, but I don't see what caused the other two issues to be able to replicate them. 

Probably my issue is just one easy way to reproduce the fault when the image plane temporarily extends and is shrunk again.

**Comment by DamirPorobic** [comment]
Ok, lets keep this one open and check later if it's fixed. Sounds easy reproducible.
