### ISSUE TITLE
Text suggestion: Line breaks within text box by pressing either the key "enter" or "ctrl+enter"

### ISSUE THREAD

**Issue by carloscadux** [ksnip/kImageAnnotator#272]
Hi,
 
I'm using ksnip build 1-1ccc20b on Windows 11. 
 
Currently, it seems there is no way to insert a line break within a text box.
 
I'd like to suggest adding line breaks insertion by pressing either the key "enter" or "ctrl+enter"
 
The suggested behavior is shown in this screen-recording (https://tinyurl.com/yxu65bvj).
 
Thanks,
Carlos

**Comment by DamirPorobic** [comment]
Have you tried `Shift+Enter`?

**Comment by carloscadux** [comment]
> Have you tried `Shift+Enter`?

`Shift+Enter` worked. Thanks!

**Comment by DamirPorobic** [comment]
Awesome!
