### ISSUE TITLE
Text annotation border-and-fill : transparency possible ?

### ISSUE THREAD

**Issue by docop** [ksnip/kImageAnnotator#276]
Hi So very the most super tool to use and very great.  But perhaps to be better : is it possible to add an alpha layer setting/ transparency setting for the Text annotation ?  The 'border and fill' option is only for color, having transparency adjustment there can be super usefull !

Thanks in advance

**Comment by DamirPorobic** [comment]
Transparancy/alpha of what? The text or background? I think this is a duplicate of https://github.com/ksnip/kImageAnnotator/issues/119

**Comment by docop** [comment]
i mean the background that came with the text edit. As the previous post 119 mean :
 ", and not have "Text with semi-transparent background" or arrow."   it was quite this function that can be best.
 so an extra setting for transparency into : 'border and fill'

**Comment by DamirPorobic** [comment]
Let's move further discussion to #119
