### ISSUE TITLE
Crop failure when mouse cursor in certain positions. 

### ISSUE THREAD

**Issue by JackDinn** [ksnip/kImageAnnotator#279]
On Manjaro KDE for quite a long time now the crop function does not work. It leaves a white area outside the crop if the mouse cursor is outside that area, to the left or bottom of it (see pic). The pic was cropped to just show the gray dropdown box but this is how it comes out after being applied & saved. I am suspecting that its due to the mouse cursor but im not 100% sure.

![ksnip_20220125-054159x](https://user-images.githubusercontent.com/5557560/150921653-f7648504-9511-4d4d-a08e-fcf5fff11f5b.png)

System:
  Host: greg-inspiron5767 Kernel: 5.10.93-1-MANJARO x86_64 bits: 64
    Desktop: KDE Plasma 5.23.5 Distro: Manjaro Linux
Machine:
  Type: Laptop System: Dell product: Inspiron 5767 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 03XWWJ v: A00 serial: <superuser required>
    UEFI-[Legacy]: Dell v: 1.4.1 date: 12/24/2020
Name            : ksnip
Version         : 1.9.2-1

**Comment by DamirPorobic** [comment]
The mouse cursor is an annotation item just like an arrow or pen stroke. When you crop, you crop just the background image so the mouse cursor stays relative to the remaining picture. Can you try deleting the mouse cursor (right click on it then select delete) and see if canvas size is adjusted correctly?

**Comment by JackDinn** [comment]
Ahh, well i never knew that it replaced the image of the mouse cursor with a moveable annotation. Yes that is the problem and now i know its easy to fix, iv just turned off the capture mouse cursor.

Thank you Sir :)

**Comment by DamirPorobic** [comment]
Glad to hear that it's working for you. :)
