### ISSUE TITLE
Middle-click on tab header closes tab

### ISSUE THREAD

**Issue by derek-shnosh** [ksnip/kImageAnnotator#280]
**Is your feature request related to a problem? Please describe.**
Not a _problem_ but typical behavior while middle clicking a tab in an application will close the tab.

**Describe the solution you'd like**
I'd like to be able to middle-click anywhere on a tab to be able to close it, helps with workflow when (reluctantly) using the mouse.

**Comment by DamirPorobic** [comment]
Implemented.

**Comment by derek-shnosh** [comment]
That was quick, thank you!

**Comment by DamirPorobic** [comment]
Thanks for testing! Yeah, I had some time today while waiting for the CI to build the plugins. Happy snipping!

**Comment by derek-shnosh** [comment]
@DamirPorobic - interesting behavior, I'm finding that _any_ mouse-click on the tab is closing it... not just the middle mouse button.

**Comment by DamirPorobic** [comment]
Oh, that’s not good. I’ll have a look into it in the morning.
________________________________

**Comment by DamirPorobic** [comment]
Should be fixed, thanks for finding this.

**Comment by derek-shnosh** [comment]
@DamirPorobic I just grabbed the latest continuous app image and it seems to still behave the same (any click will close a tab).

**Version: 1.10.0-continuous
Build: 1-5bcd0ca**

**Comment by DamirPorobic** [comment]
No, cannot confirm, works for me now. Could it be that you have started the new version without closing an already ksnip instance with Single instance mode running? Try closing all ksnip instances before starting the new one. 

The hash there looks incorrect, the last version, built yesterday around 20:00 CET has following hash:
**Version: 1.10.0-continuous
Build: 1-436db4a**

**Comment by DamirPorobic** [comment]
That's spooky, I'll check on my Linux machine later but all the packages should have the hash of the last commit:
![image](https://user-images.githubusercontent.com/12796236/152483008-c5dfddfe-25df-4863-9202-a37371b14a9b.png)

**Comment by derek-shnosh** [comment]
No idea what that was all about, but today I'm on the right build and the app is behaving as expected. 🤷🏼‍♂️

Sorry for the confusion and thanks for your help!

**Comment by DamirPorobic** [comment]
Glad that it's working for you now :)
