### ISSUE TITLE
Adding image effect does not send image change notification

### ISSUE THREAD

**Issue by SjoerdV** [ksnip/kImageAnnotator#283]
**Describe the bug**
Adding a drop shadow to an image in the editor does not constitute a change and the Save button remains greyed out

**To Reproduce**
1. make a screenshot (any)
2. Click on Effects / Drop Shadow
3. The Save button remains Greyed out

**Expected behavior**
When an effect is added (like drop shadow), this should constitute to a change of the file contents and thus trigger the option to resave

**Screenshots**
![image](https://user-images.githubusercontent.com/13275320/156763980-1ba57133-cd83-46dc-a8f0-4be08c3fd9ae.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution in case of Linux [e.g. Ubuntu]: Mint
 - Window System in case of Linux [e.g. X11]: X11
 - ksnip version [e.g. 1.8.0]: 1.9.2
 - How did you install ksnip [e.g. AppImage]: deb package

**Additional context**
none

**Comment by DamirPorobic** [comment]
True, should be a smaller issue to fix. Thanks for reporting.

**Comment by DamirPorobic** [comment]
Should be fixed now.

**Comment by SjoerdV** [comment]
Wow that's fast @DamirPorobic, don't go spoiling me now! I'll be anticipating the next release. Have a good one!
