### ISSUE TITLE
Alpha channel on marker tools is opaque

### ISSUE THREAD

**Issue by troffasky** [ksnip/kImageAnnotator#289]
**Describe the bug**
Marker tool colours in 1.10 Build: 1-84bbb9e have default alpha values of 255.

**To Reproduce**
1. Use marker in 1.9.2 or older, it doesn't completely obscure what you are marking
2. Upgrade to 1.10+ CI build
3. Use marker tools, marker now behaves like a "normal" pen

**Expected behavior**
I expect it to behave like it did in previous versions - Alpha channel is somewhere between 128-200 [total guess here - when you edit a colour in 1.9.2 there is no alpha parameter available].

**Screenshots**
![ksnip_20220327-102420](https://user-images.githubusercontent.com/13175177/160275408-94f62d4f-b75a-40b9-881b-88e2fe766672.png)
![ksnip_20220327-101757](https://user-images.githubusercontent.com/13175177/160275412-c5579ac7-0fb5-4b0f-bf44-c2f53520fc70.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Distribution in case of Linux: Tested on Debian SID and Ubuntu 21.04
 - Window System in case of Linux: KDE/X11
 - ksnip version: 1.10 CI builds
 - How did you install ksnip: Deb

**Additional context**
Here's a little bit of semantics: the way I use the "marker" tools is actually what I would call in real life a "highlighter" - it doesn't obscure the thing you are colouring over. A marker pen does. So this is NotABug in the sense that the thing called a marker now behaves like a marker :-) But the thing called a marker has an icon that looks a lot like a highlighter to me. So it's a bug.

**Comment by DamirPorobic** [comment]
Should be fixed now.
