### ISSUE TITLE
Add mouse cursor sticker

### ISSUE THREAD

**Issue by pintassilgo** [ksnip/kImageAnnotator#290]
Just like you can add arrows, markers, text, rectangles...

From what I know, the best you can get right now is to manually find a .SVG cursor on the web, add it as "Sticker" and disable "Use default stickers". But cursor added that way is giant and has wrong aspect ratio (it's *fat*), it's needed to manually resize it, not very practical.

**Comment by DamirPorobic** [comment]
@pintassilgo do you know that you can capture an existing cursor and move it around like an any other item? It's not supported evrywhere, you can try to select it and move it.

If we add cursors like items, that would also be just stickers, I would not draw them. You could resize the stickers before adding them to ksnip, have you tried that?

**Comment by pintassilgo** [comment]
> do you know that you can capture an existing cursor and move it around like an any other item?

Doesn't work for me (Manjaro KDE X11).

> You could resize the stickers before adding them to ksnip, have you tried that?

I don't know how to do that with a SVG file.

**Comment by pintassilgo** [comment]
I'll hide this comment later as offtopic, but please, how to install ocr plugin? Its release page only has deb and rpm and I'm in a Arch based distro.

Tried to build it using the same instructions in ksnip readme, but it's throwing error saying it cannot find "-lleptonica" (I have liblept.so in `/lib/`).

**Comment by DamirPorobic** [comment]
> Tried to build it using the same instructions in ksnip readme, but it's throwing error saying it cannot find "-lleptonica" (I have liblept.so in /lib/).

Sounds like we are looking for a different library name then you have there. You could try to create a link to the so file and call it libleptonica.so or something like that. Probably best, but for a long run, would be to find the Arch ksnip maintainer and ask him/her to add the ocr plugin to the Arch repo.

**Comment by DamirPorobic** [comment]
I could add this cursor sticker to the default stickers? https://openmoji.org/library/#emoji=E258

**Comment by pintassilgo** [comment]
I'm trying with this one:
https://freesvg.org/mouse-cursor-arow-fixed

But still struggling to resize it before adding to ksnip. I almost did it, but now I need to crop it.

**Comment by DamirPorobic** [comment]
Hang in there, I'm adding the cursor sticker and implementing this scaling option https://github.com/ksnip/kImageAnnotator/issues/285

**Comment by DamirPorobic** [comment]
There should be now a mouse cursor and a scaling box for stickers, hoope this resolves your use case.
