### ISSUE TITLE
Respect original aspect ratio of "stickers"

### ISSUE THREAD

**Issue by pintassilgo** [ksnip/kImageAnnotator#291]
Like the cursor I linked in #290 (btw, thanks for the fix!). It gets distorted in ksnip because it does not have equal width and height, but ksnip forces stickers to be a square. Scaling doesn't solve this issue because it maintains aspect ratio.

I know stickers are squares by definition, but currently they are the only proper way to add custom objects (images) in ksnip.

**Comment by DamirPorobic** [comment]
Implemented.
