### ISSUE TITLE
Allow to set images (non-svg) as stickers (or add a specific tool for that)

### ISSUE THREAD

**Issue by pintassilgo** [ksnip/kImageAnnotator#293]
Self explanatory title.

This would prevent all this cursor related issues I've been talking about recently (#290, #291 and #292).

Currently, the only way to add custom images is by pressing Ctrl+Shift+V (paste embedded), so it's something you always need to copy from other apps, not being practical if it's a common image you often want to add.

**Comment by DamirPorobic** [comment]
Duplicate of https://github.com/ksnip/kImageAnnotator/issues/254?

**Comment by pintassilgo** [comment]
Yes.
