### ISSUE TITLE
Sticker resizing is broken when bounding rect flipped

### ISSUE THREAD

**Issue by xTibor** [ksnip/kImageAnnotator#306]
**STEPS TO REPRODUCE**

1. Take a screenshot.
2. Add a sticker.
3. Resize the sticker so its bounding box is flipped around the horizontal or vertical axis.
4. Sticker is incorrectly rendered.

**OBSERVED RESULT**

In ksnip (latest AppImage):

https://user-images.githubusercontent.com/1627292/178153083-ab4c4923-4669-4bd0-82e7-1a83fcb12968.mp4

In Spectacle (22.04.1):

https://user-images.githubusercontent.com/1627292/178153095-f0d3d30a-086d-4b03-aeef-62d367be4768.mp4

**EXPECTED RESULT**

There are numerous ways this could be solved:

- Enforcing a minimum sticker size.
- Or normalizing the bounding box when it gets flipped.
- Or rendering flipped stickers for flipped bounding boxes.
- Or removing stickers when the bounding box gets funky.

**Comment by DamirPorobic** [comment]
Fixed by normalizing the bounding box. Thanks for reporting!
