### ISSUE TITLE
Several missing translation terms

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#312]
**Describe the bug**
Several missing translation terms

**Screenshots**

![10](https://user-images.githubusercontent.com/24946480/192278416-d08dbd62-12fc-4a6c-9382-f3a444e20f06.png)
Note: zoom tool: missing translation in tooltips

![08](https://user-images.githubusercontent.com/24946480/192278422-66cb9f9e-69ca-4a61-9d7d-b4a09be81f79.png)

![09](https://user-images.githubusercontent.com/24946480/192278424-20fe3ae3-10e1-48fe-bff0-d47b642a2c43.png)

Note: the term opacity is missing in all tools

**Desktop (please complete the following information):**
 - OS: [Windows]
 - ksnip version: [1.10.1-continuous]
 - How did you install ksnip: [zip file]

**Comment by DamirPorobic** [comment]
Translation files updated.
