### ISSUE TITLE
Release plans for Qt6 support

### ISSUE THREAD

**Issue by dflogeras** [ksnip/kImageAnnotator#330]
Hi.  We at Gentoo (and more I'd expect) are beginning to plan how to roll packages depending on kimageannotator/kcolorpicker for the eventual inclusion with plasma6/qt6 integration.  kImageAnnotator is at least used in Gwenview.

Just wondering if a release of kImageAnnotator/kColorPicker is being planned for the near future, or if we should plan to find our own snapshots in the interim?

**Comment by DamirPorobic** [comment]
I'm planing to release a version in the next couple of days.

**Comment by dflogeras** [comment]
Thanks for the quick reply.  If you'd like some additional testing prior to tagging, just poke here and I can do my best.  I should have a few cycles this week.

**Comment by DamirPorobic** [comment]
Versions have been tagged for botj kImageAnnotator and kColorPicker.
