### ISSUE TITLE
Multiple tests failing when BUILD_WITH_QT6=On

### ISSUE THREAD

**Issue by dflogeras** [ksnip/kImageAnnotator#331]
Several fails all seem to have the same root cause: that is, missing QTEST_ADD_GPU_BLACKLIST_SUPPORT_DEFS.

I checked and sure enough, QtTest/qtest.h no longer defines this in the qt6 version.   There is a note in qt's dist/changes-5.13.0 saying they got rid of it and you should remove it from your QTEST_MAIN() implementations.

I did that and the build got further along, but then failed on QLatin1Literal.  Not sure how to port that out.

**Comment by DamirPorobic** [comment]
Does this affect only the tests? Have you tried building without the tests, which you don't need for releasing.

**Comment by dflogeras** [comment]
Correct, the main library builds successfully against Qt5/Qt6. Gentoo's ebuilds do actually attempt to build a package's test-suite, so normally we do run them, but I can override that for this release.

Sorry for the misunderstanding, I'm not trying to get this fixed immediately (and I'm also happy to submit patches).  I just thought I'd log the bug so it can be visible.

**Comment by DamirPorobic** [comment]
No worries, was just asking to clarify.

@nicolasfella you haven't looked into the tests for the Qt6 port by any chance?

**Comment by heirecka** [comment]
I can't say I know everything behind the GPU_BLACKLIST thing, but I have them building and passing with Qt6 with https://github.com/ksnip/kImageAnnotator/pull/332
