### ISSUE TITLE
0.7.1 doesn't build with kcolorpicker 0.3.0

### ISSUE THREAD

**Issue by antonio-rojas** [ksnip/kImageAnnotator#336]
0.7.1 wants a `kColorPicker::kColorPicker` cmake target, which kcolorpicker 0.3.0 doesn't provide. It provides the `kColorPicker::kColorPicker-Qt*` target instead.

**Comment by DamirPorobic** [comment]
Sorry, forgot to tag a new version of kColorPicker. Coming in couple of minutes. We are dropping the `-Qt*`

**Comment by DamirPorobic** [comment]
Repushed tag and tagged kColorPicker

**Comment by antonio-rojas** [comment]
> Sorry, forgot to tag a new version of kColorPicker. Coming in couple of minutes. We are dropping the `-Qt*`

So Qt5 and Qt6 versions are no longer coinstallable?

**Comment by DamirPorobic** [comment]
No, you have to pick one.
