### ISSUE TITLE
Add config option for numbering tool to only set next number

### ISSUE THREAD

**Issue by DamirPorobic** [ksnip/kImageAnnotator#42]
Currently we can set the first number with the numbering tool. If some numbers have already been drawn, changing the start number changes all existing numbers to keep them consecutive. Users have requested to have an option to switch back to the old behavior where changing the number resulted in only changing the number of the next item.

**Comment by fnkabit** [comment]
Would it make sense to have the following behaviour instead ?
* if a number is selected, control would specify (and allow for changing) the value of the currently selected number
* if no number is selected, control would specify the value of the next number (number of items on screen + 1)

**Comment by DamirPorobic** [comment]
This is actually the behavior that was before I moved all the annotation logic to the annotator and one of the earliest ksnip supporters request this to be changed, for quite some time, so I though let's bring it back here as a config option. 

What you suggest might be more difficult to implement but the value of this feature is in my opinion rather small, so I would implement it as simple as possible and move on.
