### ISSUE TITLE
Error Resizing a Text Box

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#53]
OS: Linux Mint 19.2 x64 Cinnamon
ksnip-1.5.0.AppImage:
https://github.com/DamirPorobic/ksnip/releases/download/v1.5.0/ksnip-1.5.0.AppImage

When you resize a text box it should wrap the line automatically, but the program overlaps the words.

<a href="https://ibb.co/K51b0Js"><img src="https://i.ibb.co/K51b0Js/Captura-de-tela-de-2019-08-03-20-12-15.png" alt="Captura-de-tela-de-2019-08-03-20-12-15" border="0"></a>
<a href="https://ibb.co/frD3MLC"><img src="https://i.ibb.co/frD3MLC/Captura-de-tela-de-2019-08-03-20-12-25.png" alt="Captura-de-tela-de-2019-08-03-20-12-25" border="0"></a>

**Comment by DamirPorobic** [comment]
Yes, I see the issue here: 
![image](https://user-images.githubusercontent.com/12796236/62600299-cea29700-b8ee-11e9-94b6-41c0036c27e4.png)

**Comment by DamirPorobic** [comment]
Can you still reproduce this issue?

**Comment by antrrax** [comment]
I did the test now with version v1.6.1 appimage on linux mint 19.3 x64 cinnamon X11 and the problem continues

**Comment by DamirPorobic** [comment]
Tested this in a Min VM with latest version and can not reproduce. The steps:
1. Draw a rectangle for text 
2. Start typing text and a new line
3. Click outside the text box to finish editing 
4. Select text box
5. resize text box

What is happening: The text that is outside the resized text box is no longer visible.
What is not happening: The text is not overlapping 

![image](https://user-images.githubusercontent.com/12796236/84985794-b53cbf00-b13d-11ea-9dea-6fffc83b7419.png)

**Comment by antrrax** [comment]
I tested it now on the Mint Cinnamon 20 beta and this new version 1.7.0 fixed this problem

**Comment by DamirPorobic** [comment]
It probably was a Qt issue and you've got a new version in Mint. Glad that it's fixed now.
