### ISSUE TITLE
Add option to translate UI

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#54]
Feature request: 

Add option to translate interface:
Itens and ToolTips

**Currently only English interface:**
<a href="https://imgbb.com/"><img src="https://i.ibb.co/BZppzg1/test.png" alt="test" border="0"></a>

--------------------
**Context menu:**
<a href="https://imgbb.com/"><img src="https://i.ibb.co/GdKNSpj/new.png" alt="new" border="0"></a>

--------------------

**Crop Window:**
<a href="https://imgbb.com/"><img src="https://i.ibb.co/FbvbrsJ/crop.png" alt="crop" border="0"></a>

**Comment by DamirPorobic** [comment]
Yeah, we need to be able to translate those. I need to check first if those translations will be transferred to projects where you use the annotator as the annotator never runs for itself.

**Comment by DamirPorobic** [comment]
Weblate repository is now up and running for kImageAnnotator too.

**Comment by antrrax** [comment]
I made a new installation of Mint Cinnamon 19.3 on a real pc and the translation of the kImageAnnotator interface is not being applied in version 1.7.0 of ksnip

**Comment by DamirPorobic** [comment]
How do you install it, what binary package? Can you check if the translation files are being installed?

________________________________

**Comment by antrrax** [comment]
In mint I used the AppImage version 1.7.0

I tested it now on Windows 10 version 1.7.1 and it is translating as expected

I currently don't have access to Mint to test Version 1.7.1

**Comment by DamirPorobic** [comment]
Ok, the appImage, I know where to look at

**Comment by DamirPorobic** [comment]
Pushed a change which might fix it, haven't tested though. Can you give it a try?
