### ISSUE TITLE
Edit Text box with double click

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#60]
Ksnip is getting awesome ...

You recently added the option to edit the text box via the right mouse button.
Would it also be possible to edit the text box if we double click on it?

**Comment by DamirPorobic** [comment]
This is a tricky one, my first intention was to make it on double click but we have already something on the first click so we would need to have some kind of check, like check if first click on item if yes, then don't add new item, something like that. On the other hand it makes adding item over item impossible. We need a smart logic here.

**Comment by DamirPorobic** [comment]
Implemented by @fnkabit.
