### ISSUE TITLE
Accents still not work in text tool on Linux

### ISSUE THREAD

**Issue by antrrax** [ksnip/kImageAnnotator#61]
I use Linux Mint 19.2 x64 Cinnamon
Git clone: September 06, 2019

I did the accent test and it's still not working. I tested on the same PC with Windows 7 and Linux Mint Cinnamon and tested on another PC with Windows 10

On both Windows 7 and 10 in the Ksnip textbox tool, the keyboard appears to be set up correctly, but does not accept accents above the letters.
In Windows if I type "Alt Gr" + "Third character keys", nothing appears in Ksnip

(In other Windows applications the keyboard is normal)

<a href="https://ibb.co/8XdnFKg"><img src="https://i.ibb.co/SJdDqsw/windows.png" alt="windows" border="0"></a>

------------

In Linux Mint Cinnamon in the Ksnip textbox tool, the keyboard does not appear to be configured for the Brazilian Portuguese layout, as no accent key works, but I noticed that if I type the {"Alt Gr" + "accent key"} or {"Alt Gr" + "Shift" + "accent key"} Ksnip displays the accent, however the accent is never above the letters. (In other applications the keyboard is normal)

<a href="https://ibb.co/3pbbd34"><img src="https://i.ibb.co/1rNNQg7/linux.png" alt="linux" border="0"></a>

<a href="https://ibb.co/VCMh6zC"><img src="https://i.ibb.co/DMw6dvM/kb.png" alt="kb" border="0"></a>

$locale

LANG=pt_BR.UTF-8
LANGUAGE=pt_BR
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=

**Comment by DamirPorobic** [comment]
Now I get you, you would expect to type something like this `é`.
I think it doesn't have to do anything with your keyboard but rather with the way we detect key press in order to write the text in the text item, need to look into that in more detail.

**Comment by antrrax** [comment]
The expected behavior is that the accents are typed over the letter, and for that to happen the default is 1st we type the accent key and then the letter key. For example:
**á à á â ã ä**
But the strange thing is that on Windows and Linux the keyboard behavior was different

**Comment by antrrax** [comment]
I did the test with version 1.6.0 - 09/09/19. On Windows 7 and Windows 10 the accents are working correctly.
But on Linux Mint still didn't work, I tested the .deb version and the appimage version.
I tested on another PC with Linux mint also did not work

Note: Windows 7 and Linux Mint are on the same hardware.

**Comment by DamirPorobic** [comment]
Ok, that's something. I've just tested in a normal Linux text editor (Kate on OpenSUSE) and there I can't input accents too. Is it anywhere possible on Linux by default? Same here in this text on Github in a Firefox Browser, the usual way how I enter accents doesn't work.

**Comment by antrrax** [comment]
I installed OpenSUSE to do some testing.
When the keyboard is set to Layout English US. In the text editor Kate, I can not type the accents on the letters see in the image:
<a href="https://ibb.co/4Zm6tQ0"><img src="https://i.ibb.co/gMj59nc/kate-en.png" alt="kate-en" border="0"></a>


When I changed the keyboard to Layout: Portuguese BR, then I can type the accents on the letters as it should be.
<a href="https://ibb.co/wzPy7Xs"><img src="https://i.ibb.co/Tg7c1SL/kate-pt.png" alt="kate-pt" border="0"></a>

**NOTE: I did the same test on Linux Mint Cinnamon and the behavior was the same - on the english keyboard layout it was not possible to type the accents on the letters**

Yast:
<a href="https://ibb.co/xzpKjqX"><img src="https://i.ibb.co/qmtLsY7/yast-kb.png" alt="yast-kb" border="0"></a>
<a href="https://ibb.co/WF0x7PS"><img src="https://i.ibb.co/XpD263m/pt.png" alt="pt" border="0"></a>

----------------------------
EN-US Keyboard Layout
<a href="https://ibb.co/QX83jt0"><img src="https://i.ibb.co/ZNHp179/KB-en-us.png" alt="KB-en-us" border="0"></a>

PT-BR Keyboard Layout
<a href="https://ibb.co/7GVDhtd"><img src="https://i.ibb.co/19KNcGt/KB-pt-br.png" alt="KB-pt-br" border="0"></a>

**Comment by DamirPorobic** [comment]
Thanks for testing that. Strange, I have a German Keyboard and should be able to type the `é` or at least it work on Windows. Anyways, we need to investigate that further, need to check if we get the wrong Keys in the Key Press Event or we just pars them incorrectly.

**Comment by raphaelh** [comment]
Hi,

I can report the same problem using Xubuntu 19.10 with ksnip 1.5.10:

![image](https://user-images.githubusercontent.com/542500/73470939-f1d36e00-4388-11ea-8b9b-55c7109dac4a.png)

I cannot type the following for example : ê ô ë ö

I'm available to help you debug this

**Comment by DamirPorobic** [comment]
Thanks for reporting. I still haven't had time to look into this. Any RP are welcome.

**Comment by raphaelh** [comment]
Any idea on how to help you debug this?

**Comment by DamirPorobic** [comment]
Well, we currently use a keyPressEvent detect every single key pressed and from that we extract the letters that we insert in the TextItem. We first need to figure out if we can get the correct letter (the one with the accent) from the event, if yes, we need to check why we don't write it then. If not, we have two options:
1. Create mapping for every combination of accent and letter, then check every time an accent is pressed what the next letter is and return an entry from the mapping. Could be difficult to track all accents and create the correct mapping.
2. Inherit from QGraphicsTextItem, I believe they map correctly. Problem here is that our ItemBase class inherits already from QGraphicsItem, from which also QGraphicsTextItem inherits. We would need to check if we can extract our base functionality into it's own abstract class and let every itemType inherit from QGraphicsItem and only our TextItem from QGraphicsTextItem.

That's probably what I would do to investigate this.

**Comment by DamirPorobic** [comment]
@antrrax you mentioned that its working on Windows but not on linux, right? This would mean or handling is not that incorrect, we need to find out where the difference between linux and windows come from.

**Comment by DamirPorobic** [comment]
It looks like we have a solution for this, can you test again on your side? @raphaelh please test with latest version, not 1.5.0. The latest version you can find here https://github.com/ksnip/ksnip/releases/tag/continuous as soon as the build is done.

**Comment by antrrax** [comment]
I tested it on Mint and now it's working properly!
Thanks

**Comment by raphaelh** [comment]
It works perfectly, thanks a lot!
