### ISSUE TITLE
Icons not scaled with HiDPI 

### ISSUE THREAD

**Issue by fakhamatia** [ksnip/kImageAnnotator#77]
In 4K resolution:

![Screenshot from 2020-02-15 23-24-36](https://user-images.githubusercontent.com/20030910/74594351-9bce1e00-504a-11ea-88a1-16ba1156e4a2.png)

Ubuntu 18.04
ksnip 1.6.0

**Comment by DamirPorobic** [comment]
Icons don't scale with the rest of the the application? Any scaling there or just 4K Resolution?

**Comment by fakhamatia** [comment]
> Icons don't scale with the rest of the application?

Yes, just icons.

> Any scaling there or just 4K Resolution?

I don't understand.
![Screenshot from 2020-02-15 23-49-47](https://user-images.githubusercontent.com/20030910/74594640-e43b0b00-504d-11ea-96bd-7dec61701580.png)

**Comment by DamirPorobic** [comment]
Yeah, that's what I mean. With 4K you would have very small icons, but on your screenshot it looked like you have scaling enabled, 2x (or 200%) as it looks like. 

I'm using OpenSUSE 15.0 and with 4K Resolution and 2x Scaling on my side looks pretty normal:
![image](https://user-images.githubusercontent.com/12796236/74594770-29edd880-503a-11ea-92ba-8ddb0cde37e2.png)

You using X11 or Wayland?
Unfortunately I have Ubuntu only in VM and can't get 4K Resolution there to troubleshoot that on my side. Only thing that I could try is smaller resolution with scaling.

**Comment by DamirPorobic** [comment]
Yes, can reproduce with smaller resolution. This issue is caused by the scaling.

**Comment by fakhamatia** [comment]
> You using X11 or Wayland?

$ echo $XDG_SESSION_TYPE
x11

**Comment by DamirPorobic** [comment]
My mistake, with X11 I was not able to set the Scaling, only change the resolution. SO we have the issue with X11 and Wayland. I'm looking into it.

**Comment by DamirPorobic** [comment]
Can you check latest continuous build? I have added a fix whoch I have so far tested only under Windows. Later today I will tests against AppImage under KDE and Gnome

**Comment by fakhamatia** [comment]
It's OK, Thank you.

![Screenshot from 2020-02-20 13-42-53](https://user-images.githubusercontent.com/20030910/74924016-fc60b080-53e6-11ea-8d43-aa8c85d27cd5.png)

**Comment by DamirPorobic** [comment]
Oh, the delay imput box is still small. Will fix that too.

**Comment by fakhamatia** [comment]
![Screenshot from 2020-02-20 20-56-16](https://user-images.githubusercontent.com/20030910/74961696-bb3ac180-5423-11ea-9f0e-8a2ea95bf0bb.png)

**Comment by DamirPorobic** [comment]
Looks good now. One thing that needs to be fixed is the "Selected" border in the color picker popup. After that I think we're good.
