### ISSUE TITLE
Strange issue when typing composed characters 

### ISSUE THREAD

**Issue by RafaelLinux** [ksnip/kImageAnnotator#78]
When I use the text tool (T) and write some latin characters (like "á", "ä", "ë", and so on) cursor "jumps" a character to the right (like if I press "right cursor"). They all are got composing characters with "Shift": 
    á press "Shift + ´ " and release, press a
    ä press "Shift + ¨ " and release, press a
    ë press "Shift + ¨ " and release, press e

Environment:
OpenSUSE 15.1
KDE Plasma
All "locale" parameters are set to "es_ES.UTF-8"

**Comment by DamirPorobic** [comment]
Thanks for reporting.

**Comment by RafaelLinux** [comment]
Thanks to you for your great job!

**Comment by DamirPorobic** [comment]
What version of ksnip are you using? I've tested now with latest version 1.6.1 on OpenSUSE 15.0 and accent letters are correctly added and the cursor moved just after the new letter.
I hold shift, press one of the accent characters (nothing happens yet), release shift and the accent letter (still nothing happens), then press "a" for example, a new letter is at that point added and the cursor is next to the new letter. Seems like expected to me.

**Comment by RafaelLinux** [comment]
I tried version 1.6.2 and is working fine!!!

Thank you

**Comment by DamirPorobic** [comment]
Awesome :)
