### ISSUE TITLE
Add Number with Arrow/pointer tool

### ISSUE THREAD

**Issue by RafaelLinux** [ksnip/kImageAnnotator#79]
The "Number" tool is very practical. However, if user try to combine with arrows, result is not very "aesthetic", cause user can't change depth of objects, so if I combine a number with an arrow (in this order) the "arrow" shadow is OVER the "number" circle. So to get a good looking and useful way to combine "number" and "arrow" tools, I suggest to add a "Number with arrow" that let user to define the item that the number is pointing to.

![Ksnip - arrow suggestion](https://user-images.githubusercontent.com/13048959/74661847-0b522380-5199-11ea-9473-146d20368150.jpg)

**Comment by DamirPorobic** [comment]
Nice Idea, I like it. Simple sultion would be to have the Arrow fixed to one side. A more complex solution would be to make it adjustable in what direction it shows. Maybe some config option for that?

**Comment by RafaelLinux** [comment]
I think the "complex solution" is the more useful. If user can't select the direction, it would be not so interesting IMHO  ;)

**Comment by hprmedina** [comment]
In a more complex solution.... when click and maintaining clicking (this set the pointing direction of the arrow), the direction of the arrow is set... then moving the position of the circle moves the circle and pointing to the first click...

![image](https://user-images.githubusercontent.com/18145927/81091385-2ba69a00-8ecd-11ea-91fe-246fbdf609ac.png)

After thay you can move the circle and the arrow for giving another direction if you wisj

**Comment by RafaelLinux** [comment]
I can't repeat your steps, don't understand where my faut.

**Comment by hprmedina** [comment]
Sorry, it was only an "extension" of the "complex idea" ...it's not implemented XD.

**Comment by DamirPorobic** [comment]
It's probably going to work like current arrows only whit the additional number at the starting point. Later on you will be able to move the arrow head and number, just like with arrows.

**Comment by DamirPorobic** [comment]
This was implemented, please test and report back.

**Comment by RafaelLinux** [comment]
I downloaded latest (1.6.2) AppImage but can't find where is it implemented  :(

**Comment by DamirPorobic** [comment]
`1.6.2` is finished, there are no changes for that version anymore. New Features are added to `1.7.0 `currently, but this one will be closed and released soon too. So you feature is in `1.7.0` latest.
