### ISSUE TITLE
Make arrow size decrease with stroke size

### ISSUE THREAD

**Issue by MurzNN** [ksnip/kImageAnnotator#84]
Sometimes I need to draw small arrows, but the arrow symbol stays too large:
![image](https://user-images.githubusercontent.com/336662/78246503-f257c480-74f1-11ea-94a0-0cf685f79297.png)
Solution is to set arrow size match to stroke size. Can you fix this problem? Thanks!

**Comment by DamirPorobic** [comment]
Should be doable.

**Comment by DamirPorobic** [comment]
Done, please check and let me know if that is ok.

**Comment by MurzNN** [comment]
Thanks, much better! But with size=1 will be good to have more smaller arrow, here is example of problem:
![image](https://user-images.githubusercontent.com/336662/83488322-53315800-a4b5-11ea-8571-a2900083be51.png)
