### ISSUE TITLE
Inconsistency of project license (LGPL? GPL?)

### ISSUE THREAD

**Issue by hosiet** [ksnip/kImageAnnotator#88]
While packaging ksnip and all dependencies in Debian, the license review discovers that there are inconsistencies in project and file licensing for kImageAnnotator.

All files contain a header stating that the file is licensed under GNU Lesser General Public License version 2 or later (`LGPL-2.0+`). However, the `LICENSE` file at that top directory of the project contains a copy of GNU General Public License (`GPL-2`). They are completely different licenses with different considerations.

Could you please update the license file to correctly reflect the actual license of this project? I believe the whole project should be licensed under `LGPL-2.0+` but I'm not sure if that is intended.

**Comment by DamirPorobic** [comment]
Thanks for finding this and letting me know. Indeed it should be LGPL her, changed the `LICENSE` file to `LGPL-2.1`. 

What are you packaging? If ksnip, there we seem to have the same issue but the other way, there all the headers need to be changed to `GPL-2.0`.

**Comment by hosiet** [comment]
Thanks, I was just starting from packaging the dependency libraries; knsip itself will be packaged later. It would be great if all known issues either in kimageannotator or ksnip could be fixed soon.

**Comment by DamirPorobic** [comment]
If you mean the license stuff with „all know issues“, then yes, probably tomorrow during the day (Germany time). I‘ll check also kcolorpicker, which probably has the same issue as kimageannotator.

________________________________

**Comment by DamirPorobic** [comment]
Done, should all be correct now. kImageAnnotator LGPL3 and ksnip GPL2. Let me know if I can be of any further assistance.

**Comment by hosiet** [comment]
Thanks!
