### ISSUE TITLE
Make dropdown buttons show popup on click

### ISSUE THREAD

**Issue by hprmedina** [ksnip/kImageAnnotator#89]
Using gnome, the dropdown buttons not working, I can use only default feature on every button.

![image](https://user-images.githubusercontent.com/18145927/81083891-26445200-8ec3-11ea-8660-7e22edc5a7d2.png)

But when I use "cinnamon" those buttons works fine, showing me all suboptions.
Using 1.6.1 build 949-792716e
Gnome 3.26.1

but options under "New" works fine. Maybe the problem is just on the toolbar
![image](https://user-images.githubusercontent.com/18145927/81084369-c4381c80-8ec3-11ea-9e00-746f3f863ada.png)

**Comment by hprmedina** [comment]
True!!!

1 second delay shows the subitems, thanks!!! but, it should be instantaneous!!!! I have two friends, and they happens the same, XD. I will tell them.

![image](https://user-images.githubusercontent.com/18145927/81089069-dfa62600-8ec9-11ea-8bac-1339f4ddc053.png)

**Comment by DamirPorobic** [comment]
I'll try to fix that in one of the following releases.

**Comment by DamirPorobic** [comment]
I've added a code changed, it's in the latest ksnip version.
