### ISSUE TITLE
Canvas background color configurable

### ISSUE THREAD

**Issue by vaunchag** [ksnip/kImageAnnotator#91]
FR:
When implementing #90 (to avoid cutting out of border annotations), the filling on the image border is white.

This color could be made configurable. In this way, that filling can be chosen more according to the contents of the image and/or the target background where the image may be later inserted.

Transparence setting should be also possible.

The chosen color (or conventional tiles if transparence is chosen) should be reflected in the GUI (in place of the current white shown):
- This is so to be able to preview the final results (e.g. be able to check if there is enough contrast with the chosen annotation colors).
- By the way, this permits honoring a user preference, even only when displaying (i.e. even when no out of border annotation is used).

The preference should be persistent across restarts of the application.

Ponder if it is worth puting this configuration in the main toolbar, or puting it more "buried" in the preferences.

**Comment by DamirPorobic** [comment]
Do you think that all the white region should get this color or only the canvas as discussed in #92.

That would be this professionally yellow marked region:
![image](https://user-images.githubusercontent.com/12796236/103310570-37287180-4a18-11eb-87d8-c98a66f0ebdd.png)

It could be a way to visualize how large the canvas is which otherwise is not visible outside the Modify Canvas tool.

**Comment by vaunchag** [comment]
Not sure if I understand the 2 options, sorry... The white region you have marked looks to me like the canvas, I think I'm missing something.

Citing your last sentence "a way to visualize how large the canvas is otherwise is not visible outside the Modify Canvas tool.", I agree that it is quite useful to "constantly" visualize the reach of the canvas (in normal view), to know what is going to be saved.

One of the current oddities in ksnip when you capture a small area with white background (in some UIs this can often happen, since white is a usual background color). In that case, you don't see where your area ends when visualizing in ksnip:

![image](https://user-images.githubusercontent.com/64960827/103346804-6fba6080-4a95-11eb-9d13-177a5d21b784.png)

You effectively see the border indirectly when activating the crop tool, but the rest of the time you are "blind".

When I opened this FR, one of the aims for configuring the background color (or appearance) of the "external" area was precisely in orden to be able to preview constantly the final results (limits) of what was going to be saved (while editing).

But I see now that I mixed two things: if this external background color is made equal to the "filling" color used for added canvas (for #90 and #92), it will make in this case the border of this added parts invisible again (at least in normal view).

So these should be two different (configurable) things:

1. Color (including permitting transparency) to be used when filling extra canvas (for #90 and #92). Currently white.
2. Color or appearance of the external background seen in ksnip when the captured area is small. Currently also white.

For 2, maybe a default more suitable than current one would do the job. A typical (and also ugly) chessboard pattern? A less usual color than pure white? Or maybe a different strategy: a visible border seen in any case in this situation? Shouldn't be easily confused with a normal border present in the image or drawn by the user, for example by using a (also ugly) dashed border, as Gimp currently does.

**Comment by DamirPorobic** [comment]
Yes, exactly, that's the two things that need to be addressed. I'm against an additional border, as you said, they're ugly. For now I think I'm going with setting color for canvas background (which get's into the final image) and setting color for the view (that is the white region that doesn't get into the final image). I think I would prefer keeping both by default white, just keep it consistent with the current look, also there are other users of the annotator, like KDE Spectacle, so don't want to step on anyone's toes. In the settings you should be able change both default colors and, maybe, change temporally the canvas background in the modify canvas tool. 

Also, I think you're not using the latest version of ksnip, just in case you're not aware :)

**Comment by vaunchag** [comment]
Sounds very reasonable.

The desired canvas fill color may depend typically on the particular capture, so would be great to have this "at hand" as you propose with the "maybe".

Your proposal offers it only when modifying the canvas and that the color change should be temporal. But maybe it makes more sense to "expose" this fill color in the normal UI:

- I see this quite similar to the fact that one choses color for annotations (lines, fills, text), and changes them sometimes to adapt to a diferent "captured image mood", and this change gets persistent (for good and for bad)... I see more  or less the fill canvas choice in the same category of choices.
- Besides, this setting applies also when canvas is resized automatically on save (#90). And also there, it is pertinent to possibly adapt that color to the image (and previewing its effects before saving/closing).

I also understand that this is adding clutter to the normal UI, and that the "modify canvas" is a reasonable place also to put it. But in this case, I'm not sure if I would at least remove the "temporality" of the change.

**Comment by vaunchag** [comment]
(sorry for the double post: I've updated my ksnip version, and seen lots of interesting additions, thanks for pointing this to me! :-) )

**Comment by DamirPorobic** [comment]
> I see this quite similar to the fact that one choses color for annotations (lines, fills, text), and changes them sometimes to adapt to a diferent "captured image mood", and this change gets persistent (for good and for bad)... I see more or less the fill canvas choice in the same category of choices.

I don't see it like that, I think that most users will be drawing on the captured image. What you have here is a use case but not one that every user has or not at least on daily basis. 

> Besides, this setting applies also when canvas is resized automatically on save (#90). And also there, it is pertinent to possibly adapt that color to the image (and previewing its effects before saving/closing).

You have now two options to set it, the first is from settings, this becomes your default for every new tab. Then, you can change it for a specific tab that is already open via the "Modify Canvas" and while in the "Modify Canvas" View, you can also preview, size and color and only after clicking Apply it is going to be applied to the current tab. 

> I also understand that this is adding clutter to the normal UI

This one is very importent to me, I'm trying to avoid creating a mini gimp UI that is too advanced for the standard user.

> But in this case, I'm not sure if I would at least remove the "temporality" of the change.

The one under settings is permanent and is default for all new tabs that are opened after that change. The one under `Modify Canvas` affects only the current tab, you can think of it as a way to overwrite the default for the tab that you are currently looking at. 

This feature is now implemented, check out the continuous build in 30min from now, the new package should be available. Give it a try, let me know what you think. Under `Setting > Annotator > Canvas Color` you can set the default and under `View > Modify Canvas` you can change the color of the current canvas.

**Comment by vaunchag** [comment]
Thanks a lot for implementing this. I also see your points.
 
Sorry, I'm trying to test, but not able to. In previous build, only the .dmg was available. And the build from yesterday stays in 5 assets (no .deb nor .AppImage). Something seems wrong with the Travis CI. I will keep trying to try :-)

**Comment by DamirPorobic** [comment]
That is strange indeed. TravisCI is migrating some of its infrastructure, might be related to to this.

**Comment by DamirPorobic** [comment]
@vaunchag Just checked, I can see them [here](https://github.com/ksnip/ksnip/releases/tag/continuous):
![image](https://user-images.githubusercontent.com/12796236/103633238-bd2b4780-4f45-11eb-927d-4dec7c3a1444.png)

**Comment by vaunchag** [comment]
Thanks! I've just dowloaded it, before it disappears again ;-)

**Comment by vaunchag** [comment]
Works great! Both the global preset and the current-tab only.

Setting it to transparent, at least in Linux, is a little bit unintuitive for casual users: one has to "know" that this is done by setting "Alpha channel" to 0 (or intermediate). But this happens also for any other color chosen in the interface. I assume that it is the price to pay for using the vanilla color picker (a decision that I understand perfectly).

Awesome work. Many many thanks!
