### ISSUE TITLE
Add tab context menu for 'close all tabs' and 'close other tabs'

### ISSUE THREAD

**Issue by MurzNN** [ksnip/kImageAnnotator#93]
With last changes ksnip create new screenshots in new tabs - this is good feature, but at end of day we see many unneeded tabs in interface (`Capture 1` ... `Capture 123`), and we need to close each separately.

For solve this problem will be good to add button "close all tabs" that will close all via one click.

Also, maybe, add some "auto-close tab timeout" feature, that will auto-close very old tabs (eg that not changed more than 48 hours)?

**Comment by DamirPorobic** [comment]
I've added a context menu and you can close now all tabs. I'm still looking into the shortcut for closing a tab.

**Comment by MurzNN** [comment]
Thanks! Also will be good to have the separate button on panel for close all tabs, maybe at right of tabs line?

**Comment by DamirPorobic** [comment]
For now there will be no separate close button, it would require rewriting the TabWidget. Also, it's very common to have such button but I think the ContextMenu on tabs is a suitable workaround.

**Comment by DamirPorobic** [comment]
I've added a shortcut and you have now five options to close tabs from context menu:

1. Current tab (this shortcut)
2. Other tabs (all tabs expect the one you clicked)
3. All Tabs
4. All tabs left of the one you clicked
5. All tabs right of the one you clicked
